### ISSUE TITLE
Blacklist doesn't work with 'ember-cli-babel' options key

### ISSUE THREAD

**Issue by Soliah** [babel/ember-cli-babel#114]
Was scratching my head why this wasn't working. Blacklisting doesn't seem to work with 5.2.3/4 and the options key `'ember-cli-build'`.

Example repo demonstrating: https://github.com/Soliah/es6-test

**Comment by rwjblue** [comment]
`blacklist` was part of the `babel` config option (only `compileModules` and `includePolyfill` were moved to `'ember-cli-babel'` config key). I submitted https://github.com/Soliah/es6-test/pull/1 to show what I mean.

Closing this for now (assuming I was correct above).  Happy to reopen if that doesn't solve the issue...
