### ISSUE TITLE
Determine mechanism to add plugins after `babel-preset-env` plugins.

### ISSUE THREAD

**Issue by rwjblue** [babel/ember-cli-babel#119]
Currently, all user supplied plugins (in `options.babel.plugins`) are added *before* the `babel-preset-env` plugins ([see final plugin construction code here](https://github.com/babel/ember-cli-babel/blob/d40c01114df28af6b108d4e66b448261d34da6c7/index.js#L158-L162)). I believe that this is the correct default position for all plugins (as most want to operate on the raw source AST).

However, there are some circumstances where you want to write plugins that operate on the AST *after* the various babel transforms have occurred. The prime example of this is the `babel6-plugin-strip-class-callcheck` plugin, which removes the `_classCallCheck` for production code (which is used by ember-data).

I can think of a couple of possible solutions here, we just need to decide what to implement.

* Option A: this emulates babel@5's setup (which would have `{ transformer: ***, position: 'after' }`).

```js
this.options.babel.plugins.push({
  plugin: require('babel6-plugin-strip-class-callcheck'),
  postion: 'after'
});
```

* Option B

```js
this.options.babel.pluginsAfterTransformation = [
  require('babel6-plugin-strip-class-callcheck')
];
```

I'm sure there are additional options, and I'm happy for suggestions.

**Comment by rwjblue** [comment]
I'm leaning more towards Option B personally (I'd rather not confuse folks with the babel@5 syntax).

**Comment by Turbo87** [comment]
what would be the resulting order then?

- `plugins`
- `preset-env`
- AMD modules plugin
- `pluginsAfterTransformation`

I tend to prefer the second option too

**Comment by cibernox** [comment]
The question here is: Is possible for someone to want a plugin to be placed before/after other specific plugin? In case we want a DAG.

Perhaps its not that finegrained to the plugin level, but maybe after `preset-env` but before the `modules`.

**Comment by rwjblue** [comment]
Modules are processed before the rest of preset env at the moment (I'm open to changing that if y'all disagree). So I don't really think we are offering any options other than before or after preset env. 

I looked into using a DAG last night, and it would be easy enough to implement but there isn't a defining property we could use for the before/after (e.g. Babel plugins don't have a `name` property). Which means it would be very difficult...

**Comment by rwjblue** [comment]
> what would be the resulting order then?

* plugins
* AMD modules plugin
* preset-env
* pluginsAfterTransformation (or better name)
