### ISSUE TITLE
generators throws exception

### ISSUE THREAD

**Issue by flecno** [babel/ember-cli-babel#12]
I try to use ES6 generators in a new clean ember-cli project but it doesn't run in the browser because of `Uncaught ReferenceError: regeneratorRuntime is not defined`. It seems there is a missing global/dependency in my service? 

```js
function* testGenerator(fixtures) {
  for(let i = 0, max = fixtures.length; i < max; ++i) {
    yield foo(fixtures[i]);
  }
}
```
6to5 generates this source for my example:
```js
var testGenerator = regeneratorRuntime.mark(function testGenerator(fixtures) {
  var i, max;
  return regeneratorRuntime.wrap(function testGenerator$(context$1$0) {
    while (1) switch (context$1$0.prev = context$1$0.next) {
      case 0:
        i = 0, max = fixtures.length;
      case 1:
        if (!(i < max)) {
          context$1$0.next = 7;
          break;
        }
        context$1$0.next = 4;
        return foo(fixtures[i]);
      case 4:
        ++i;
        context$1$0.next = 1;
        break;
      case 7:
      case "end":
        return context$1$0.stop();
    }
  }, testGenerator, this);
});
```

I'm using `ember-cli@0.1.12` and  `ember-cli-6to5@3.0.0`

**Comment by stefanpenner** [comment]
Ya, we need to detect and inject the regenerator runtime yet.

**Comment by sebmck** [comment]
@stefanpenner Not really. I'm open to an API suggestion though.

**Comment by stefanpenner** [comment]
@amasad you did something similar to this with regenerator right? Thoughts?

**Comment by sebmck** [comment]
@stefanpenner You're probably thinking of facebook/regenerator#155. I can easily add in an API that reports whether or not the regenerator runtime is necessary I'm just not sure what it should be, possibly passing a function that's called as an option?

**Comment by stefanpenner** [comment]
> @stefanpenner You're probably thinking of facebook/regenerator#155. I can easily add in an API that reports whether or not the regenerator runtime is necessary I'm just not sure what it should be, possibly passing a function that's called as an option?

As I am enjoying regenerator + async await for writing tests (and want this), I will be preparing an issue for @sebmck. The idea also dove tails nicely into some other plans. I'll be AFAK for the next few days, but I hope to get the issue out sunday night or monday.

**Comment by stefanpenner** [comment]
https://github.com/babel/ember-cli-babel/issues/24 / https://github.com/babel/ember-cli-babel/pull/6

**Comment by palimpsests** [comment]
@flecno and/or @stefanpenner  were you able to resolve this? I just started a new ember-cli project and am running into the exact same issue when trying to define a generator `Uncaught ReferenceError: regeneratorRuntime is not defined`

**Comment by flecno** [comment]
On 07/09/2015 10:45 PM, Zach Zibrat wrote:
> @flecno <https://github.com/flecno> and/or @stefanpenner 
> <https://github.com/stefanpenner> were you able to resolve this? I
> just started a new ember-cli project and am running into the exact
> same issue when trying to define a generator |Uncaught
> ReferenceError: regeneratorRuntime is not defined|
> 
> — Reply to this email directly or view it on GitHub 
> <https://github.com/babel/ember-cli-babel/issues/12#issuecomment-120139700>.
>
> 
Sorry, I haven't tried it again for now.

**Comment by stefanpenner** [comment]
today you need to include the runtime yourself:

https://github.com/stefanpenner/ember-jobs/blob/master/app/index.html#L20-L23

**Comment by palimpsests** [comment]
ok, thanks very much, I'll try this. Just before you posted this, I was able to get my generator working by using the Bower package `babel-polyfill` and then including in the Brocfile:

`app.import('bower_components/babel-polyfill/browser-polyfill.js', { prepend: true });`

**Comment by ecengels88** [comment]
For those who are running into this issue, see: https://github.com/babel/ember-cli-babel#polyfill
