### ISSUE TITLE
v6.0.0-beta.9 not working with ember-cli v2.12.X

### ISSUE THREAD

**Issue by alexlafroscia** [babel/ember-cli-babel#129]
I'm trying to upgrade `ember-ajax` to use Babel 6, like the other default Ember Addons.  However, it seems like something is going wrong with transpiling the modules.

https://travis-ci.org/ember-cli/ember-ajax/jobs/215353720#L452

**Comment by binoculars** [comment]
I believe you need to use `export default from ...` instead of `export { default } from ...`

**Comment by alexlafroscia** [comment]
Hmm interesting. That makes sense -- I'll check that out./

**Comment by alexlafroscia** [comment]
That's not it; the `export { default } from ...` is correct.

**Comment by stefanpenner** [comment]
taking a look

**Comment by stefanpenner** [comment]
the issue appears to be `ember-ajax` `node` sniffing https://github.com/ember-cli/ember-ajax/blob/master/addon/-private/utils/url-helpers.js#L12

**Comment by stefanpenner** [comment]
updated https://github.com/ember-cli/ember-ajax/pull/266 to work

**Comment by alexlafroscia** [comment]
Awesome, thanks so much for digging into this @stefanpenner!
