### ISSUE TITLE
Please make sure to add a preprocessor to in `dependencies`

### ISSUE THREAD

**Issue by wellington1993** [babel/ember-cli-babel#130]
Hi,

I got this message when I do: 'ember build'. Please look this:

```
➜  my_project git:(my_branch) ✗ ember build
DEPRECATION: Addon files were detected in `~/projetos/abc/my_project/node_modules/ember-load-initializers/addon`, but no JavaScript preprocessors were found for `ember-load-initializers`. Please make sure to add a preprocessor (most likely `ember-cli-babel`) to in `dependencies` (NOT `devDependencies`) in `ember-load-initializers`'s `package.json`.
cleaning up...
Built project successfully. Stored in "dist/".

```

I need to do something? It's normal?

My versions:

> └── ember-cli-babel@5.2.4 
> ember-cli: 2.12.1
> node: 4.7.2
> os: linux x64

Sorry my poor English and Thanks.

**Comment by rwjblue** [comment]
The error message states that it is about `ember-load-initializers` addon not being properly setup, this was fixed in https://github.com/ember-cli/ember-load-initializers/pull/37.  All you should need to do is update to a newer version. 😸
