### ISSUE TITLE
Incorrect "Addon files were detected" message

### ISSUE THREAD

**Issue by kellyselden** [babel/ember-cli-babel#135]
My addon only has `.gitkeep` files in both the app and addon folders, yet I get this message:

```
DEPRECATION: Addon files were detected in `/home/travis/build/kellyselden/ember-cli-funnel/addon`, but no JavaScript preprocessors were found for `ember-cli-funnel`. Please make sure to add a preprocessor (most likely `ember-cli-babel`) to in `dependencies` (NOT `devDependencies`) in `ember-cli-funnel`'s `package.json`.
```

https://travis-ci.org/kellyselden/ember-cli-funnel/jobs/224806561#L1136

**Comment by rwjblue** [comment]
The warning is actually coming from ember-cli (not related to babel), but I thought we were only looking for "js" files.

**Comment by kellyselden** [comment]
Migrated to https://github.com/ember-cli/ember-cli/issues/7154
