### ISSUE TITLE
How to remove deprecation "has overridden the `this.options.babel`"

### ISSUE THREAD

**Issue by kellyselden** [babel/ember-cli-babel#136]
Are there docs on how to remove

```
DEPRECATION: Ember CLI addons manage their own module transpilation during the `treeForAddon` processing. `ember-cli-funnel` (found at `C:\code\ember-cli-funnel`) has overridden the `this.options.babel` options which conflicts with the addons ability to transpile its `addon/` files properly. Falling back to default babel configuration options.
```

My addon uses `this.app.options.funnel`, but doesn't touch babel.

**Comment by kellyselden** [comment]
https://github.com/kellyselden/ember-cli-funnel/blob/master/index.js#L20

I see now that it is overwriting `this.options = `. I saw you PR some fixes a while back, I think you came up with a convention?

**Comment by rwjblue** [comment]
Closing for now, I believe this has been fixed.

@kellyselden - Let me know if I'm mistaken...
