### ISSUE TITLE
Provide better annotation to broccoli-babel-transpiler.

### ISSUE THREAD

**Issue by rwjblue** [babel/ember-cli-babel#146]
Currently, all of the broccoli-babel-transpiler nodes show up as `Babel` because we are not passing in a more specific annotation (and therefore it uses `node.constructor.name`).

**Comment by stefanpenner** [comment]
What would be an example of a better annotation. (I'm just curious what you specifically had in mind)

**Comment by rwjblue** [comment]
Addressed in #154, default annotation is `Babel: parent-addon-or-project-name`.
