### ISSUE TITLE
NodeJS 8.0.

### ISSUE THREAD

**Issue by johnunclesam** [babel/ember-cli-babel#147]
```
error ember-cli-babel@6.1.0: The engine "node" is incompatible with this module. Expected version "^4.5 || 6.* || 7.*".
error Found incompatible module
```

**Comment by stefanpenner** [comment]
updating CI now

**Comment by stefanpenner** [comment]
fixed on master actually: https://github.com/babel/ember-cli-babel/blob/master/package.json#L72

Likley just needs a release

**Comment by johnunclesam** [comment]
yes, please.

**Comment by stefanpenner** [comment]
https://github.com/babel/ember-cli-babel/pull/148

**Comment by stefanpenner** [comment]
merged, but we are having some issues releasing to NPM: https://github.com/babel/ember-cli-babel/issues/153
