### ISSUE TITLE
can't release, npm is having troubles

### ISSUE THREAD

**Issue by stefanpenner** [babel/ember-cli-babel#153]
@rwjblue you may be the only one able to release, as I am apparently no longer an owner?

**Comment by hzoo** [comment]
@stefanpenner are you on the babel slack, I moved a bunch of packages to the babel org so possible that the permissions are gone for some packages

**Comment by stefanpenner** [comment]
@hzoo thanks, the org move did cause the issue. But not a big deal, thanks for guiding me through using it! :)

**Comment by stefanpenner** [comment]
@rwjblue FYI, this is uses babel's org stuff now, and is on the ember team. You, me and @Turbo87 are maintainers of this now.

**Comment by hzoo** [comment]
Yeah it's a free thing now and you don't have to use a scope. I had to transfer all of our 100s of package to the org and the permissions got kinda messed up in the process! https://www.npmjs.com/docs/orgs/

**Comment by Turbo87** [comment]
uh, awesome! I didn't know that :)
