### ISSUE TITLE
includePolyfill in an Ember Addon

### ISSUE THREAD

**Issue by theseyi** [babel/ember-cli-babel#156]
According to the README.md you can add a polyfill to an Ember Addon by setting the option  "in an addons index.js." This is somewhat unclear as adding this option as either part of the exported object i.e.
```javascript
module.exports = {
  name: 'addon-name',

  'ember-cli-babel': {
    includePolyfill: true
  }
}
```
or appending to the config object in the config hook:
```javascript
module.exports = {
  name: 'addon-name',

  config() {
    return Object.assign(config, {
        'ember-cli-babel': {
        includePolyfill: true
      }
    });
  }
}
```

does not work.

Can the documentation/README be updated with the correct approach?

**Comment by nightire** [comment]
Try: 

```js
module.exports = {
  name: 'addon-name', 
  options: {
    'ember-cli-babel': {
      includePolyfill: true
    }
  } 
}
```

**Comment by theseyi** [comment]
Perfect! thanks @nightire
