### ISSUE TITLE
returning debug macro statements results in an error

### ISSUE THREAD

**Issue by toranb** [babel/ember-cli-babel#168]
I started the upgrade to ember-cli-babel v6.6.0 for one of my addons recently and found that when I destructure assert from `@ember/debug` the compiled output omits it for some odd reason. I'm writing to better understand if what I found is truly a regression of some kind or just me doing something I shouldn't be (and getting away with it prior to the v6.6.0 upgrade).

The import below is what doesn't work for dev or test builds any longer

```js
import { assert } from '@ember/debug';
```

note: before using ember-cli-babel v6.6.0 I would pull assert from the global Ember

```js
import Ember from 'ember';

const { assert } = Ember;
```

The difference is that prior to this import change and ember-cli-babel v6.6.0 my test build would run and assert would work as designed. Now I get an error saying `assert is not defined` when the [test](https://github.com/ember-redux/ember-redux/pull/133/files#diff-bc44365758bf3ddad57dbbe3d7ecaf8eR110) runs.

note: in dev tools when I capture this failure at test time and look at the imports / variable defs at the top of my module I don't see assert

![screen shot 2017-07-26 at 6 53 07 am](https://user-images.githubusercontent.com/147411/28619705-4d187488-71cf-11e7-8acb-3ae63bcf0734.png)

Notice in the actual source for that file I have assert imported

![screen shot 2017-07-26 at 6 56 13 am](https://user-images.githubusercontent.com/147411/28619756-9c2fd156-71cf-11e7-9b16-3e5a6857f3e2.png)

I'm using ember-cli 2.13.0, ember 2.13.3 with node 6.10.2 and ember-cli-babel v6.6.0. For a full and complete repro checkout the branch I have up for the [PR](https://github.com/ember-redux/ember-redux/pull/133) that bumps it to ember-cli-babel v6.6.0

**Comment by rwjblue** [comment]
The fact that the assert import is removed is not the issue, instead there is a problem with the prod/debug stripping plugin that we need to track down. Can you share the full transpiled output of embed-redux/connect module?

I currently suspect that computedReduxProperty using implicit returning arrow functions is the issue (Specifically, we don't handle the `return assert(....)` correctly).  A work around for now that you could test would be to change `computedReduxProperty`'s `set` into a block form arrow function (or plain function).

**Comment by rwjblue** [comment]
OK, thanks for sharing.  My suggested work around should work and avoid the errors you are seeing:

```js
function computedReduxProperty(key, getProps) {
  return computed({
    get: () => getProps()[key],
    set: () => { assert(`Cannot set redux property "${key}". Try dispatching a redux action instead.`); }
  });
}
```

I have created https://github.com/chadhietala/babel-plugin-debug-macros/issues/46 to track fixing the underlying babel plugin.

**Comment by toranb** [comment]
@rwjblue thanks for both the workaround and opening the real issue w/ babel-plugin-debug-macros
