### ISSUE TITLE
Transpilation doesn't work for tests when hinting is turned on

### ISSUE THREAD

**Issue by hoboman313** [babel/ember-cli-babel#169]
I'm on the latest everything ( ember, ember-cli-babel, etc.. ).

Running into a really weird issue where the app works great with hinting turned off, but when I turn it on, the transpilation suddenly fails.

> Build failed.
> The Broccoli Plugin: [BroccoliMergeTrees: TreeMerger (appTestTrees)] failed with:
> SyntaxError: ...
> Unexpected token (57:8)
>   55 |       return EmberObject.create({
>   56 |         isSelected: (selectedStates.indexOf(state.id) !== -1),
>   57 |         ...state
>        |         ^
>   58 |       });
>   59 |     });

I do have "transform-object-rest-spread" set up as in my ember-cli-build.js as instructed in the README here. Even if I comment out the spread operator stuff, tests will still fail with messages like: Global error: SyntaxError: Unexpected token 'const' at http://localhost:7357/assets/tests.js, line 8". Strangely enough, everything works perfectly if I just set hinting to false in the ember-cli-build.js. Wtf?

**Comment by rwjblue** [comment]
I helped someone with a similar issue a couple months ago, most likely you have a misbehaving linter. I have PR'ed ~ 4 different style linters that were causing this issue, you should check into yours to confirm you have latest versions.

**Comment by rwjblue** [comment]
See https://github.com/ember-cli/ember-cli/issues/7063 and cross linked PR's.

**Comment by hoboman313** [comment]
Oh! You are correct. It was due to a misbehaving linter. We switched over to eslint-plugin-ember-suave but forgot to https://github.com/DockYard/eslint-plugin-ember-suave#upgrading-from-ember-suave

It would appear that ember-suave was causing my breakage. Thanks!
