### ISSUE TITLE
`import * as foo from '@ember/some-module';` does not work

### ISSUE THREAD

**Issue by buschtoens** [babel/ember-cli-babel#170]
The [`import` statement](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) supports importing all named exports into an object.

For example, instead of this

```js
import {
  alias as computedAlias,
  and as computedAnd,
  // ...
} from '@ember/object/computed';
import { decoratedPropertyWithRequiredParams } from '../utils/decorator-macros';

export const alias = decoratedPropertyWithRequiredParams(computedAlias);
```

you could just do this

```js
import * as computed from '@ember/object/computed';
import { decoratedPropertyWithRequiredParams } from '../utils/decorator-macros';

export const alias = decoratedPropertyWithRequiredParams(computed.alias);
```

But apparently, the latter does not work. :slightly_frowning_face: 

```
Could not find module `@ember/object/computed` imported from `ember-decorators/object/computed`
```

**Comment by rwjblue** [comment]
We would need to handle wildcard import in babel-plugin-ember-modules-API-polyfill. This seems reasonable to me though. We would need to check if the specified module contains only exports from a single namespace or multiple. If multiple namespaces we would have to build up the intermediate POJO that would be used.

**Comment by buschtoens** [comment]
Thanks for the pointer. Closing in favor of https://github.com/ember-cli/babel-plugin-ember-modules-api-polyfill/issues/16.
