### ISSUE TITLE
v6.8.0 is having trouble with test helpers

### ISSUE THREAD

**Issue by kellyselden** [babel/ember-cli-babel#178]
Both failures have to deal with not finding (custom) test helpers.

https://travis-ci.org/ember-vr/ember-aframe-camera-extras/jobs/264830153#L2352
https://travis-ci.org/kellyselden/ember-datetimepicker/jobs/264831720#L2342

**Comment by rwjblue** [comment]
https://github.com/ember-cli/babel-plugin-ember-modules-api-polyfill/pull/19 fixes
