### ISSUE TITLE
Ember.warn transpilation error

### ISSUE THREAD

**Issue by simonihmig** [babel/ember-cli-babel#184]
When `Ember.warn` is imported with the new module API, something weird happens during transpilation. Not sure if it's related to some babel plugin, and if so which, so created the issue here for now...

Here is a reproduction repo: https://github.com/simonihmig/ember-warn-transpilation.
It contains two examples of `Ember.warn` usage, one with the new imports, and one (`warn2`) with globals: https://github.com/simonihmig/ember-warn-transpilation/tree/master/app/utils

These files transpile as follows:
```js
define('ember-warn-transpilation/utils/warn', ['exports'], function (exports) {
  'use strict';

  Object.defineProperty(exports, "__esModule", {
    value: true
  });
  exports.default = warn;
  function warn() {
    (true && Ember.emberWarn(...arguments));
  }
});
define('ember-warn-transpilation/utils/warn2', ['exports'], function (exports) {
  'use strict';

  Object.defineProperty(exports, "__esModule", {
    value: true
  });
  exports.default = warn2;
  var emberWarn = Ember.warn;
  function warn2() {
    emberWarn.apply(undefined, arguments);
  }
});
```

The interesting part is this: `(true && Ember.emberWarn(...arguments));`:
* The spread operator is not transpiled
* `Ember.emberWarn` is not a thing
* `true &&` ???

Because of the spread usage, the whole app breaks with a syntax error in older browsers (IE11).
The globals based module transpiles correctly though...

**Comment by pzuraq** [comment]
Under the hood, the new debug macros are being transformed by this babel plugin: https://github.com/chadhietala/babel-plugin-debug-macros

The plugin strips all of the debug helpers at build time in production builds, so its behavior is different than other modules which are compiled. Based on this, and a quick glance at the tests for that transform, I'm not sure it took renaming imports into account. It is also probably breaking transpilation of `arguments`. To be fair, chances are wrapper functions like the ones in the linked issue aren't necessary, so I wouldn't say this is a super high priority bug, but it should probably be fixed at some point

**Comment by simonihmig** [comment]
@pzuraq thanks for pointing out that babel plugin. I was thinking it had to do with debug stripping, but was not aware of the actual plugin...

Seems this is actually a duplicate of https://github.com/chadhietala/babel-plugin-debug-macros/issues/47, so closing this here now!

> I'm not sure it took renaming imports into account

Does not happen only with renamed imports, see the linked issue above!
