### ISSUE TITLE
Please add fetch() polyfill so IE 11 will behave somewhat more intelligently

### ISSUE THREAD

**Issue by RyanNerd** [babel/ember-cli-babel#189]
The `fetch()` polyfill is **intentionally** missing from core-js (please add it so IE isn't quite as stupid)
https://github.com/zloirock/core-js

> window.fetch is not a cross-platform feature, in some environments it makes no sense. For this reason, I don't think it should be in core-js.

**Comment by rwjblue** [comment]
Thanks for stopping by! This doesn’t seem like a bug in ember-cli-babel though, so I’m going to close this. 

Fear not though! Adding fetch to your project is _really_ easy!  

```
ember install ember-fetch
```

🎉😎
