### ISSUE TITLE
Is there anyway to configure the version of babel used by this cli addon.

### ISSUE THREAD

**Issue by santosh-kalidindi** [babel/ember-cli-babel#202]
I want to try out Babel 7.0 beta but currently, the ember-cli-babel tool uses broccoli-babel-transpiler which is fixed to version 6 of Babel. Any way around this to use babel 7? Also, are there plans to support Babel 7 which is releasing very soon?

**Comment by rwjblue** [comment]
a number of betas have already been published, please test them 😄

**Comment by santosh-kalidindi** [comment]
Ah, I see there is a PR for Babel 7. Completely missed that. Thank you for the prompt response.
