### ISSUE TITLE
Parsing error: Cannot find module '@babel/helper-get-function-arity'

### ISSUE THREAD

**Issue by JHKennedy4** [babel/ember-cli-babel#203]
"ember-cli-babel": "^6.10.0"

I'm seeing this error from an in-repo-addon installing using yarn workspaces. I've deleted all of my node_modules several times, as well as our yarn.lock file. Reinstalling doesn't seem to fix the error.

Anyone seen this before? Know anything about how to solve it?

**Comment by rwjblue** [comment]
Sorry for missing this issue 😞 

I believe that this was almost certainly an issue with transitive dependencies being out of sync.
