### ISSUE TITLE
Sourcemaps not generated on production build

### ISSUE THREAD

**Issue by khell** [babel/ember-cli-babel#207]
No sourcemaps are generated when building with `ember build --environment production`. Sourcemaps are generated if built with `ember build`. Using `ember` 2.16.3 and `ember-cli-babel` 6.12.0.

**Comment by rwjblue** [comment]
Yep. Sourcemaps are disabled for production builds, but you can turn them back on. 

Checkout https://ember-cli.com/user-guide/#source-maps for more details.

**Comment by khell** [comment]
Thanks @rwjblue, I jumped the gun on this one. We deleted this property between changes somehow between Ember upgrades.
