### ISSUE TITLE
travis https://travis-ci.org/babel/ember-cli-babel

### ISSUE THREAD

**Issue by stefanpenner** [babel/ember-cli-babel#21]

**Comment by gordonkristan** [comment]
I added .travis.yml in 7ffc1faa59a2ef16b1c433d46cc0c64f5e60616e and added the status image in 257023a92f6f93700a45e9b13f3f81771ade7ae9. (And of course I forgot to link to this issue in the commits.) I used the configuration from Ember-CLI as a starting point and everything seems to be working. Anything else we need to do for this?

**Comment by stefanpenner** [comment]
@sebmck maybe you need to enable something? I thought it was working pre-name change.

**Comment by sebmck** [comment]
@stefanpenner travis might have gotten reset when the org changed.

**Comment by sebmck** [comment]
@stefanpenner It's enabled, last travis build was 4 hours ago and:

![screen shot 2015-02-27 at 7 44 40 am](https://cloud.githubusercontent.com/assets/853712/6401442/8c206608-be54-11e4-86a2-45ba2e935c15.png)

**Comment by stefanpenner** [comment]
perfect!
