### ISSUE TITLE
Module compilation in 7.0.0-beta.2 includes the full file paths

### ISSUE THREAD

**Issue by dfreeman** [babel/ember-cli-babel#226]
If I upgrade to `ember-cli-babel@7.0.0-beta.2` in a fresh app (generated from `ember-cli@3.1.4`), the module names for everything under `app` include the full path on disk where they originated, e.g.

```js
define("/Users/dfreeman/Desktop/Scratch Code/babel-7-app/babel-7-app/app", ["exports", "/Users/dfreeman/Desktop/Scratch Code/babel-7-app/babel-7-app/resolver", "ember-load-initializers", "/Users/dfreeman/Desktop/Scratch Code/babel-7-app/babel-7-app/config/environment"], function (_exports, _resolver, _emberLoadInitializers, _environment) {
  "use strict";
  // ...
```

Presumably module names should match those generated by `ember-cli-babel@6.x`?

**Comment by rwjblue** [comment]
Yes, definitely a bug. Thank you for reporting!

**Comment by dfreeman** [comment]
Probably related to https://github.com/babel/babel/pull/8044? Poking around, both `amd-name-resolver` and `@babel/plugin-transform-modules-amd` (the latter via `@babel/core`'s `getModuleName`) seem like they're assuming relative paths.

**Comment by rwjblue** [comment]
This has been resolved (a loooooong time ago), closing...
