### ISSUE TITLE
buildBabelOptions returns some things that aren't valid babel options

### ISSUE THREAD

**Issue by ef4** [babel/ember-cli-babel#227]
`annotation` and `throwUnlessParallelizable` are returned by `buildBabelOptions()`, but they aren't really babel options, they're broccoli-babel-transpiler options.

This came up because in [ember-auto-import](https://github.com/ef4/ember-auto-import) I'm trying to automatically configure a babel parser based off the app's babel configuration.

I think these options should be kept separate from the real babel options.

**Comment by ef4** [comment]
Just hit another example, which is the weird not-really-a-plugin entry with `_parallelBabel` that we put into the plugins list.

**Comment by rwjblue** [comment]
@ef4 Think we should avoid adding them and make a private internal API for when we have to talk to broccoli-babel-transpiler?

**Comment by ef4** [comment]
Or at least keep them together under a single property within the Babel config, so it’s easier to split them back out.

**Comment by rwjblue** [comment]
FWIW, this will be resolvable with https://github.com/babel/ember-cli-babel/pull/371.

**Comment by lifeart** [comment]
may be related https://github.com/ef4/ember-auto-import/issues/267
