### ISSUE TITLE
Dynamic property keys error

### ISSUE THREAD

**Issue by cibernox** [babel/ember-cli-babel#23]
I have this code in `app/pretender/config.js`
```js
import Ember from 'ember';
import config from '../config/environment';

var defaultPageSize = config.APP.defaultPageSize;

// Example usage:
//   servePaginated('school', { filterField: 'name' })
function servePaginated(type, { filterField }) {
  let pluralizedType = Ember.String.pluralize(type);
  return function(store, request) {
    let results = store.findAll(type);
    let filter = request.queryParams.filter;
    if (filter && filter.length > 1) {
      filter = filter.toLowerCase();
      results = results.filter(s => s[filterField].toLowerCase().indexOf(filter) > -1);
    }
    let pagedResults = results.slice(0, defaultPageSize);
    return {
      meta: {
        total: results.length,
        page: 1
      },
      [pluralizedType]: pagedSchools
    };
  }
}
```

I'm pretty sure that this code is correct, and in fact this code works in babejs.io [live test page](https://babeljs.io/repl/#?experimental=true&playground=false&evaluate=true&loose=false&spec=false&code=import%20Ember%20from%20'ember'%3B%0Aimport%20config%20from%20'..%2Fconfig%2Fenvironment'%3B%0A%0Avar%20defaultPageSize%20%3D%20config.APP.defaultPageSize%3B%0A%0A%2F%2F%20Example%20usage%3A%0A%2F%2F%20%20%20servePaginated('school'%2C%20%7B%20filterField%3A%20'name'%20%7D)%0Afunction%20servePaginated(type%2C%20%7B%20filterField%20%7D)%20%7B%0A%20%20let%20pluralizedType%20%3D%20Ember.String.pluralize(type)%3B%0A%20%20return%20function(store%2C%20request)%20%7B%0A%20%20%20%20let%20results%20%3D%20store.findAll(type)%3B%0A%20%20%20%20let%20filter%20%3D%20request.queryParams.filter%3B%0A%20%20%20%20if%20(filter%20%26%26%20filter.length%20%3E%201)%20%7B%0A%20%20%20%20%20%20filter%20%3D%20filter.toLowerCase()%3B%0A%20%20%20%20%20%20results%20%3D%20results.filter(s%20%3D%3E%20s%5BfilterField%5D.toLowerCase().indexOf(filter)%20%3E%20-1)%3B%0A%20%20%20%20%7D%0A%20%20%20%20let%20pagedResults%20%3D%20results.slice(0%2C%20defaultPageSize)%3B%0A%20%20%20%20return%20%7B%0A%20%20%20%20%20%20meta%3A%20%7B%0A%20%20%20%20%20%20%20%20total%3A%20results.length%2C%0A%20%20%20%20%20%20%20%20page%3A%201%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%5BpluralizedType%5D%3A%20pagedResults%0A%20%20%20%20%7D%3B%0A%20%20%7D%0A%7D)

The error message is `Error: Line 23: Unexpected token [`, making reference to ` [pluralizedType]: pagedResults`.

How can I help trace down this?

**Comment by stefanpenner** [comment]
which version of babel is installed for you?

**Comment by cibernox** [comment]
Latest (4.1.0)

**Comment by stefanpenner** [comment]
I cannot seem to replicate this, can you try a `nom` and report back?

**Comment by stefanpenner** [comment]
@cibernox ping!

**Comment by cibernox** [comment]
I forgot about this!  I'll try later

**Comment by cibernox** [comment]
I confirm that is fixed. I couldn't try the exact same code because the codebase has evolved, but I've tried a very similar example and now it works. 
Not sure if the bug was fixed in a recent release or the bug never existed, but anyway seems alright.

Closing this
