### ISSUE TITLE
dynamic polyfil inclusion

### ISSUE THREAD

**Issue by stefanpenner** [babel/ember-cli-babel#24]
Goals:

Have babel report to us which files/modules depend on which polyfils, Babel may accomplish this by merely appending an import for the polyfil/dep the current module depends on. This would enable subsequent build-tooling to pull in only the polyfils that are needed, and isolate them to the module that explicitly depended on them.

This would help reduce the duplication caused by the small support algorithms currently inlined. 

``` js
var _temporalAssertDefined = function (val, name, undef) { if (val === undef) { throw new ReferenceError(name + " is not defined - temporal dead zone"); } return true; };

var _temporalUndefined = {};

var _defineProperty = function (obj, key, value) { return Object.defineProperty(obj, key, { value: value, enumerable: true, configurable: true, writable: true }); };
```

Example:

given

``` js
let b = Symbol('foo')
let a = {
  [b]() {

  }
}
```

I would love to see something like:

``` js
import _temporalAssertDefined, { _temporalUndefined } from 'babel/temporal-assert-defined';
import _defineProperty from 'babel/defineProperty'
import Symbol from 'babel/core-js/symbol' // or something

var b = _temporalUndefined;
var a = _temporalUndefined;

b = Symbol("foo");
a = _defineProperty({}, _temporalAssertDefined(b, "b", _temporalUndefined) && b, function () {});
```

Todo:
- [x] flesh this out more.

Questions:
- [ ] should babel report back what features the module needs?
- [x] should babel just drop an import and let the rest of the build system derive what is needed?
- [x] does each support algorithm now need to be in its own module (i think so)

**Comment by stefanpenner** [comment]
cc @sebmck thoughts?

**Comment by sebmck** [comment]
@stefanpenner Have you seen the [runtime](https://babeljs.io/docs/usage/runtime/)? Since core-js is now [modular](https://github.com/zloirock/core-js/releases/tag/0.7.0) it's totally within reason to abstract the helpers into individual modules too.

**Comment by stefanpenner** [comment]
@sebmck yes, its pretty close. Our system parses the es6 imports though, to decide what to include in the final build. Currently with `module` transpiling disabled, I am unsure how runtime will handle it. If it just inserted the `es6` import statements, that should handle our needs.

**Comment by sebmck** [comment]
@stefanpenner Yup that's how it works internally. It just outputs an `import` and the `modules` transformer picks it up. Should already work and if not it'd require very minimal code changes.

**Comment by stefanpenner** [comment]
> @stefanpenner Yup that's how it works internally. It just outputs an import and the modules transformer picks it up. Should already work and if not it'd require very minimal code changes.

awesome. I believe the last time I looked into this, it did not. So apparently I have not been keeping up with the changes. You are a worldwind of productivity :)

I'll try this setup out, and report back.

**Comment by sebmck** [comment]
Yep, the import is getting lost somewhere. *Should* be trivial to include.

**Comment by sebmck** [comment]
There we go.

```javascript
import _babelHelpers from "babel-runtime/helpers";
import _core from "babel-runtime/core-js";
var b = _core.Symbol("foo");
var a = _babelHelpers.defineProperty({}, b, function () {});
```

**Comment by stefanpenner** [comment]
Rad.

**Comment by amasad** [comment]
:+1: this is awesome

**Comment by sebmck** [comment]
/cc @zloirock

Would it be possible to make the library functionality modular?

**Comment by sebmck** [comment]
Made the helpers modular.

**script.js**

```javascript
class Foo extends Bar {}
```

```sh
$ babel --optional runtime script.js
```

```javascript
"use strict";

var _classCallCheck = require("babel-runtime/helpers/class-call-check")["default"];

var _inherits = require("babel-runtime/helpers/inherits")["default"];

var Foo = (function (_Bar) {
  function Foo() {
    _classCallCheck(this, Foo);

    if (_Bar != null) {
      _Bar.apply(this, arguments);
    }
  }

  _inherits(Foo, _Bar);

  return Foo;
})(Bar);
```

**Comment by zloirock** [comment]
@sebmck if I understand the question correctly, second example https://github.com/zloirock/core-js#commonjs . For prevent global namespace pollutons, `require('core-js/as-library')` should be called at first. Separation into modules and API is not fully finished.

**Comment by sebmck** [comment]
@zloirock Yeah, should have reworded my question better sorry. I was asking if it was currently possible or will be in the future to do `core-js/library/symbol` etc.

**Comment by zloirock** [comment]
@sebmck Not sure about the same api: for example, what should be available on `core-js/library/object/keys` - ES5 shim for `Object.keys` or only ES6 shim for accepting primitives? `core-js/library/array` - all ES5, ES6 statics, ES6 prototype, ES7, core-js methods? All features now available by namespaces / modules names, for example:
```js
require('core-js/as-library');
var Symbol = require('core-js/es6/symbol');
var from = require('core-js/es6/array/statics').from;
var includes = require('core-js/es7/proposals').Array.includes;
```
But api / modules structure isn't finished, possible conflicts, I think, I will change it to something like:
```js
var Symbol = require('core-js/library/es6/symbol');
var from = require('core-js/library/es6/array/from');
var includes = require('core-js/library/es7/array/includes');
```

**Comment by sebmck** [comment]
@zloirock Yup, that looks great. Exactly what I (and most likely @stefanpenner envisioned), awesome work!

**Comment by stefanpenner** [comment]
> (and most likely @stefanpenner envisioned), awesome work!

yes, this is exactly it.  If babel can inject these imports we are golden.

**Comment by sebmck** [comment]
@stefanpenner Once the `core-js` library is modular it'll be trivial.

**Comment by sebmck** [comment]
FYI the prerequisite stuff for this has been done on the Babel side, anything else?

**Comment by stefanpenner** [comment]
> FYI the prerequisite stuff for this has been done on the Babel side, anything else?

nope, I don't believe so. We are working currently on the selective build functionality in ember-cli itself. 

I suppose we can provide an interim solution in the short term.

**Comment by ksnyde** [comment]
> I suppose we can provide an interim solution in the short term.

Would love an interim solution if that's possible. Doesn't need to be optimal, just want PhantomJS to pass my tests for now.

**Comment by kottenator** [comment]
How is it going with this issue? Will the polyfill be enabled in the next `ember-cli` version (1.13.2)

**Comment by stefanpenner** [comment]
> How is it going with this issue? Will the polyfill be enabled in the next ember-cli version (1.13.2)

if you reinstall node_modules you will have a version that allows manual opt-in of the polyfil.

Note: It does not include dynamic inclusion + tree shaking, with is the long term goal of this issue.

**Comment by raido** [comment]
What's here left to do?

**Comment by bertdeblock** [comment]
Going to close this as polyfill support was removed in v8.
