### ISSUE TITLE
Cannot read property 'defineProperty' of undefined

### ISSUE THREAD

**Issue by teakap** [babel/ember-cli-babel#245]
After update from ember-cli-babel: 5.2.8  to ember-cli-babel: 6.17.1. I get an error, either specific to 'link-to' but it's actualy on every page. 

```javascript

	Object.defineProperty(exports, "__esModule", {
		value: true
	});
	var Controller = Ember.Controller,
	    computed = Ember.computed,
	    observer = Ember.observer,
	    isEmpty = Ember.isEmpty,
	    inject = Ember.inject,
	    run = Ember.run,
	    on = Ember.on,
	    testing = Ember.testing,
	    String = Ember.String,
	    Object = Ember.Object;
	exports.default = Controller.extend({
         ......
        )};
```

```json

// ember-cli-build.js

'babel': {
  loose: true,
   plugins: [
     transform-object-rest-spread
    ]
},

```

**Comment by rwjblue** [comment]
The issue here is that you are redefining `Object` (via `var Object = Ember.Object;`), Babel 6 doesn't really work with that (as it tries to then use `Object.defineProperty`  which isn't "a thing"). You will need to update your code to avoid defining an `Object` variable (or update to babel@7).

**Comment by teakap** [comment]
Updating to babel@7 didn't help. But refactoring the code to not import `Object` from ember works :) Thanks!

**Comment by buschtoens** [comment]
FWIW it's somewhat conventional to import the Ember Object as 

```js
import EmberObject from '@ember/object';
```

**Comment by teakap** [comment]
Awesome thank you! I am closing this issue.
