### ISSUE TITLE
peer dependency warning

### ISSUE THREAD

**Issue by dcyriller** [babel/ember-cli-babel#246]
Hello 👋 

While developing an addon, I got this peerDependency warning:
```
warning "ember-cli-babel > babel-plugin-debug-macros@0.2.0-beta.6" has unmet peer dependency "@babel/core@^7.0.0-beta.42"
```

Should it be considered as an issue?

**Comment by jameshahn2** [comment]
I'd like to know as well.

**Comment by MatthewPringle** [comment]
Causes crashes in Corber, the Ember / Cordova app maker.

**Comment by dcyriller** [comment]
I can't repreduce anymore. Closing then. If someone wants to reopen, let me know.

> Causes crashes in Corber, the Ember / Cordova app maker.

To fix that, I would have tried to install `@babel/core@^7.0.0-beta.42` as a dependency.

**Comment by saurabhsrivastava01** [comment]
warning "ember-cli-code-coverage > ember-cli-babel > babel-plugin-debug-macros@0.2.0" has unmet peer dependency "@babel/core@^7.0.0-beta.42".
