### ISSUE TITLE
Polyfill/Core-JS not Included with Versions 7+

### ISSUE THREAD

**Issue by spencer516** [babel/ember-cli-babel#247]
The latest versions of this repo do not appear to include the `core-js` polyfill when configuring: 

```js
'ember-cli-babel': {
  includePolyfill: true
}
```

...in the `ember-cli-build.js` file. 

Here's a branch demonstrating the issue, with a failing test: https://github.com/spencer516/babel-issue/tree/babel-7

Here's the same, but with version `6.16`, with a passing test: https://github.com/spencer516/babel-issue/tree/babel-6

**Comment by ggayowsky** [comment]
We make fairly extensive use of `.flatMap` in our application and trying to upgrade to 3.6 through ember-cli-update has broken our application because proposal polyfills are no longer included (even with `includePolyfill` set)

Would be nice to either get this old functionality back somewhat or suggesting a work around (could always just polyfill myself)

**Comment by rwjblue** [comment]
Hmm, I'm really sorry about this. I must have messed something up while migrating. 

I'll try to dig in and see what is going on...

**Comment by Frozenfire92** [comment]
Also ran into this when doing an upgrade

**Comment by Frozenfire92** [comment]
It appears to be from this PR https://github.com/babel/babel/pull/8440

From the polyfill docs https://babeljs.io/docs/en/babel-polyfill

> This will emulate a full ES2015+ environment (no < Stage 4 proposals)

However according to MDN .flat / .flatMap is Stage 4 finished
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat#Specifications
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap#Specifications

so it may be an issue of babel needing to update

However I think it would be good for the ember community if we made it easy to include the proposals from the ember-cli-babel config

I messed around with it for a bit today but wasn't able to get .flatten/.flatMap again

**Comment by pzuraq** [comment]
@ggayowsky FWIW you _should_ be able to import those like Babel recommends with [ember-auto-import](https://github.com/ef4/ember-auto-import) I believe.

**Comment by ggayowsky** [comment]
@pzuraq I tried the ember auto import with no success. (Maybe I wasnt pointing to the right package?) I believe I ended up having to import the .ember-cli-build using a cjs transform.

@Frozenfire92 I got this working and will post my solution tomorrow when I am at a computer if I remember

**Comment by Frozenfire92** [comment]
@ggayowsky friendly bump :)

**Comment by ggayowsky** [comment]
@Frozenfire92 Here is my solution.

Install the cjs transform addon (https://github.com/rwjblue/ember-cli-cjs-transform):

`ember install ember install ember-cli-cjs-transform`

Import the file in `ember-cli-build.js`:
```
    // ember-cli-build.js
    app.import('node_modules/core-js/fn/array/flat-map.js', {
        using: [{ transformation: 'cjs', as: 'flat-map-polyfill' }]
    });
```

In app.js, import the module (using the alias you defined)
```
    // app.js

    // TODO: Remove when flat-map & flat reach stage 4
    // https://github.com/tc39/proposal-flatMap
    import 'flat-map-polyfill';
```

**Comment by Frozenfire92** [comment]
@ggayowsky thanks for your response, that worked for me

**Comment by ggayowsky** [comment]
@rwjblue I don't know who is the maintainer of this package, but my recommadation would be to close this issue as it is not a problem with ember-cli-babel, but a breaking change in babel 7 where by the polyfills does not automatically included polyfills for < Stage 4 proposals (as @Frozenfire92 mentioned above).

@spencer516 and the example he included is just that flatMap is not included with the polyfills file.

I have posted a work around / solution for including < stage 4 proposals that should help with the migration from ember-cli-babel 6.x.x to 7.x.x

**Comment by spencer516** [comment]
Closing as this per the above!

**Comment by ggayowsky** [comment]
Anybody following this thread for the `flatMap` polyfill should know that running `yarn upgrade ember-cli-babel` should update the babel-polyfill dependency to at least v7.4.0 which now includes flatMap (so you should be able to remove my work around)
