### ISSUE TITLE
Array.prototype.flat polyfill is missing

### ISSUE THREAD

**Issue by yratanov** [babel/ember-cli-babel#278]
Hello, I'm using `"ember-cli-babel": "^7.7.3"`

 `array.flat` in Edge browser throws an error, while `array.flatMap` is working.

**Comment by yratanov** [comment]
may be related with: 

https://github.com/babel/babel/issues/9749

**Comment by Exelord** [comment]
I confirm. Any progress on this issue?

**Comment by Exelord** [comment]
Babel polyfill has been deprecated. (https://github.com/babel/babel/tree/master/packages/babel-polyfill)

We should upgrade this package to use core-js explicitly.

**Comment by Exelord** [comment]
@rwjblue any plans moving to core-js 3? :)

**Comment by rwjblue** [comment]
I haven't really looked into it much, but off the cuff I would think that we would follow suit with Babel and remove the polyfilling. 

Folks would then use something like ember-auto-import to get these polyfills like the [@babel/polyfill site suggests](https://babeljs.io/docs/en/next/babel-polyfill.html).

**Comment by boris-petrov** [comment]
@rwjblue - we just hit the same issue (`flat` missing). I don't understand your comment - is there something we can do right now as users or we have to wait for `ember-cli-babel` to be updated?

**Comment by dbashford** [comment]
Also curious if there is something that could be done now

**Comment by pzuraq** [comment]
One option is to use https://github.com/pzuraq/ember-cli-babel-polyfills, just updated it to use the latest `core-js` and confirmed it has `Array.flat`, plus it ensures that the polyfills are only included in legacy browsers by using `no-module` in a smart way 😄

**Comment by Exelord** [comment]
Awesome. Yep that's the solution :)

**Comment by dbashford** [comment]
That gets `flat` in (via `core-js/stable`), if I was interested in all the `esnext` stuff as well, should I just be importing `core-js` myself? Or might that be something ember-cli-babel-polyfills or eventually ember-cli-babel may support?

**Comment by bertdeblock** [comment]
Going to close this as polyfill support was removed in v8.
