### ISSUE TITLE
Test hangs when using ES6 class in ember cli 0.2.0 addon 

### ISSUE THREAD

**Issue by mikkelfish** [babel/ember-cli-babel#29]
Hello, I'm trying to make an ember cli addon that uses ES6 classes. 

When running `ember test` or `ember serve` (and going to localhost:4200/tests) the build looks like it succeeds but hangs without the tests executing. 

There are no error messages or warnings, it simply freezes with the line "Built project successfully. Stored in "$PATH\tmp\class-tests_dist-cKugYfpG.tmp".

This behavior is replicable with the most simple of ES6 classes, so I assume that there is an issue with the transpiler. 

Thanks.

**Comment by stefanpenner** [comment]
Sounds like you may have a phantom phantoms process and tested is puking

**Comment by mikkelfish** [comment]
Can you comment in some more detail?

This is reproducible for me by literally just creating a new add on (`ember test` succeeds) and then adding a file to to addons directory like so

````
export class TestFactory {
	constructor() {

	}
}
````

Investigating a bit further and the test completes when it is in the app directory instead. 

Perhaps all items in the addon directory have to be Ember ones? I am trying to bundle utils that go through the whole cli build process, but could always process them separately if required.

**Comment by stefanpenner** [comment]
@mikkelfish can you provide a demo app the demostrate this.

**Comment by mikkelfish** [comment]
https://github.com/mikkelfish/ember-babel-test-error-demo

Thanks for your help.

**Comment by gordonkristan** [comment]
I can reproduce this issue now as well (I've seen it before but I couldn't reproduce). If you download [this addon](https://github.com/gordonkristan/ember-computed-indirect) and try to add some ES6 syntax to `addon/utils/indirect.js`, you'll find that the tests hang.

I haven't had much time lately but I'm going to try to look into this today.

**Comment by stefanpenner** [comment]
This isn't a bug,  rather ember-cli-babel must be included as a `dependency` not a `devDependency` if used in an add-on.

At first this may appear strange, but actually it is just how NPM Works™,
given:

* `my-cool-app` depends on `my-addon`
* `my-addon` devDepends on `other-module`

when my-cool-app installs its dependencies, `other-module` is omitted. As such, we must:

* `my-cool-app` depends on `my-addon`
* `my-addon` **depends** on `other-module`

Now, given that, it still appears strange that our add-on, who contains the node_module/my-addon cannot use it. Well, this boils down to the `dummy` app trying to mimic how a real app would consume dependencies, and automatically omits devDependencies to prevent post-release confusion.
