### ISSUE TITLE
ParentNode.append polyfill is missing

### ISSUE THREAD

**Issue by boris-petrov** [babel/ember-cli-babel#290]
[This method](https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/append) is not available in Firefox 47 and it is not polyfilled by `ember-cli-babel` when `includePolyfill` is set to `true`. Am I missing something or is this omission a bug?

**Comment by buschtoens** [comment]
`includePolyfill` only includes the `core-js`-based polyfill for missing JS language features, e.g. `Set`.

`append` is a DOM feature. You could use [`ember-cli-polyfill-io`](https://github.com/alexlafroscia/ember-cli-polyfill-io) to polyfill the DOM.

**Comment by boris-petrov** [comment]
@buschtoens - thanks for the answer. I don't understand why polyfilling is so difficult. :D Do you know whether [ember-cli-babel-polyfills](https://github.com/pzuraq/ember-cli-babel-polyfills) includes missing such DOM features in addition to the JS ones?

**Comment by buschtoens** [comment]
AFAIK it does not, as it also only uses `core-js`. But I've had great success with polyfill.io so far.

**Comment by boris-petrov** [comment]
@buschtoens - how exactly do you use `polyfill.io` and `ember-cli-polyfill-io`? It looks to me as a service that should be used at runtime, not at build-time, or am I missing something?

**Comment by buschtoens** [comment]
Correct. All (usual) polyfills are used at runtime, even the `includePolyfill` one. Enabling `includePolyfill` basically just adds and extra JS file to the `vendor.js` bundle, that contains all the polyfills.

Using polyfill.io you include an extra `<script>` tag that loads a JS file from the polyfill.io service, that includes the polyfills.

**Comment by boris-petrov** [comment]
Ah, so you are importing the polyfills from their own CDN, you're not bundling them up in your own distribution? In that case why do you need `ember-cli-polyfill-io` at all?

**Comment by buschtoens** [comment]
You could just add the `<script>` tag yourself in `index.html`, right! But this is a semi-standardized way of doing it. Whatever floats your boat. 🤷‍♀ 😄

**Comment by boris-petrov** [comment]
I see. Thank you very much for the information!
