### ISSUE TITLE
Request:

### ISSUE THREAD

**Issue by stefanpenner** [babel/ember-cli-babel#3]
i believe we wil; be switching ember-cli proper to 6to5 as esnext + 6to5 are joining forces.

I would love to offer my time to help you maintain this project, if you are interested let me know.

**Comment by gordonkristan** [comment]
Yeah that would be great. Although I feel like it'll be mostly me helping you. :) I just started using Ember CLI recently, but I'd love to get to know more about it and get involved. Are there any specific features required before this can be used with Ember CLI by default?

**Comment by stefanpenner** [comment]
Awesome :)

Stuff inside `6to5`, for example it currently requires several native extensions, which has a native extension which for portability reasons we try are best to avoid. But our own use-cases don't touch those code-paths.

Additionally 2.5.0 pulls in a buggy core-js which has some issues currently.

Stuff we should do on this side.

- [ ] cut a new release
- [ ] add simple smoke test
- [ ] add travis
- [ ] add appveyor

**Comment by stefanpenner** [comment]
@gordonkristan i would love to cut a new release today. Is is possible I can become a maintainer of the npm package?

**Comment by gordonkristan** [comment]
Yes, I'm sorry. I've had this in my inbox I've just been busy. I'll give you access to this repo now. How can I make you a maintainer of the NPM package?

**Comment by gordonkristan** [comment]
@stefanpenner I figured out how to add you as a maintainer, so you should be able to push a new release now. Let me know if you need anything else in the meantime.

If I have time tonight, I want to write some smoke tests and get this set up with Travis.

**Comment by stefanpenner** [comment]
@gordonkristan awesome thanks! :)

**Comment by gordonkristan** [comment]
@stefanpenner Just out of curiosity, how would you go about writing a smoke test for this? I can see writing smoke test for the `getOptions` function, but it seems like writing a test for the actual tree compilation would be fairly complicated. Is there a standard way of testing addons like this? (Didn't see any tests for the Coffeescript or SASS addons.)

**Comment by stefanpenner** [comment]
for an ember-addon, I would recommend using the generate dummy app, using some es6 code, and then asserting the app and that feature that uses es6 loaded and ran correctly.  A nice integration test.
