### ISSUE TITLE
[BUG] arrow functions with Ember.computed have this as undefined

### ISSUE THREAD

**Issue by sivakumar-kailasam** [babel/ember-cli-babel#30]
Declaring a computed property as

```
fullName: Ember.computed('firstName', 'lastName', ()=>{
    return this.get('firstName') + ' ' +this.get('lastName');
})
```

it is transpiled into,

```
define('hello-world/components/a-name', ['exports', 'ember', 'hello-world/templates/components/a-name'], function (exports, Ember, layout) {

	'use strict';

	var _this = undefined;

	exports['default'] = Ember['default'].Component.extend({
		firstName: "sivakumar",

		lastName: "kailasam",

		fullName: Ember['default'].computed("firstName", "lastName", function () {
                      return this.get("firstName") + ' ' +this.get("");
		})

	});

});
```

 ```_this  = undefined``` seems to be wrong to me, is this a genuine issue or am I using arrow functions in a wrong way?

//cc @stefanpenner

**Comment by rwjblue** [comment]
I believe that the transpilation is correct.  At the time that the `Ember.computed(()=>{})` bit is processed `this` is the module scope (which is `undefined` due to being in `"use strict"` mode).  Ember ensures that the computed is called with the correct `this` context, no `=>` is needed here.

**Comment by sivakumar-kailasam** [comment]
@rwjblue My bad. Played around the [interactive babel editor](https://babeljs.io/repl) and understood how the transpilation works in this and few more cases :smile:

**Comment by stefanpenner** [comment]
as soon as the spec settles, we will get/enable annotations, which will likely unlock the following syntax

```js
class Foo extends Ember.Object {
  @dependsOn('firstName', 'lastName')
  get fullName() {
    ...
  }
}
``

**Comment by sivakumar-kailasam** [comment]
yeah can't wait for that to be out :smile: feels more natural.

**Comment by stefanpenner** [comment]
ya, we are working to nail down some of the other semantics, but hopefully soon :)

**Comment by bartocc** [comment]
@rwjblue when you say "no () => { } is needed here", do you mean we MUST use "function() {}" instead or is there another way ?

**Comment by bartocc** [comment]
@sivakumar-kailasam I'd be interested to know if you managed to have computed properties work with fat arrow functions in the end

**Comment by sivakumar-kailasam** [comment]
@bartocc I didn't. I'm planning to use @rwjblue's [ember-computed-decorators](https://github.com/rwjblue/ember-computed-decorators) which is a step towards what @stefanpenner had mentioned

**Comment by gordonkristan** [comment]
@bartocc Yes, you _must_ use the old-style anonymous function, not the arrow functions. Arrow functions, by definition, are bound to their lexical scope and the scope _cannot_ be changed. If you need to access `this` in your property, an arrow function simply won't work.

**Comment by bartocc** [comment]
Thx guys. things are clear now ;-)

**Comment by githubSathishkumar** [comment]
does this problem solved now?
