### ISSUE TITLE
ember-cli-qunit is deprecated

### ISSUE THREAD

**Issue by dmzza** [babel/ember-cli-babel#303]
[ember-cli-qunit](https://github.com/ember-cli/ember-cli-qunit) was deprecated some time ago. This is the advice given to move to `ember-qunit`:

> ### Migrating to ember-qunit
> 
> To upgrade from ember-cli-qunit@4 to ember-qunit@4 perform the following:
> 
> #### yarn
> 
> `yarn remove ember-cli-qunit`
> `yarn add -D ember-qunit`
> Update `tests/test-helper.js` to replace any imports from `ember-cli-qunit` with an import from `ember-qunit`.

I'm happy to make a PR for this if there are no objections.

**Comment by rwjblue** [comment]
👍👍sounds great to me 😄
