### ISSUE TITLE
Optional Chaining plugin not works in ember engine

### ISSUE THREAD

**Issue by RakChamp25** [babel/ember-cli-babel#304]
<img width="1288" alt="Screenshot 2019-11-04 at 4 18 05 PM" src="https://user-images.githubusercontent.com/31966737/68116185-384b3500-ff20-11e9-80f7-a99b54c52f45.png">

Optional Chaining plugin works in Ember App. But when I use the optional chaining operator(?.) in ember engine build gets failed.

FYI: I am in ember cli babel version : 7.11.1 and i have installed plugin separately

[Source](https://github.com/RakChamp25/my-work) for reference
@rwjblue

**Comment by gabrielgrant** [comment]
AFAICT this no longer occurs (I'm not getting a compiler error), but it fails at runtime for optional methods with "TypeError: _this$args3.onChange is not a function" -- see details in #332
