### ISSUE TITLE
for...of.... transpiled into an iterator that phantomjs does not recognise

### ISSUE THREAD

**Issue by dagda1** [babel/ember-cli-babel#31]
I have the following code:
```
for(let action of listenables) {
  let key, callBackName, localName;
```
That gets transpiled into:
```
for (var _iterator = listenables[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step =   _iterator.next()).done); _iteratorNormalCompletion = true) {
  var action = _step.value;
```
This works fine in chrome but fails in phahtomjs which does not recognise iterators.

**Comment by stefanpenner** [comment]
this requires core-js, which you must bring along as a polyfil. Currently that is manual, but we plan to do this automatically/transparently: https://github.com/babel/ember-cli-babel/issues/24

**Comment by stefanpenner** [comment]
closing this as part of $24

**Comment by dagda1** [comment]
is it still the case that all of ```core-js``` needs included or none or is there included?  I could not tell by reading #24.

**Comment by stefanpenner** [comment]
@dagda1 you need to include the parts you need, or the whole thing. Until we doit automatically

**Comment by dagda1** [comment]
How would I include ```core-js``` or are there any docs on this?

**Comment by stefanpenner** [comment]
please look to: https://github.com/zloirock/core-js

**Comment by dagda1** [comment]
great, thanks
