### ISSUE TITLE
Should we move ember-cli-version-checker to devDependancies?

### ISSUE THREAD

**Issue by QuantumInformation** [babel/ember-cli-babel#32]
Perhaps we should move ember-cli-version-checker to devDependancies? I tried to upgrade this addon using the steps for upgrading a cli app but get an error:

`Cannot find module 'ember-cli-version-checker'`

**Comment by stefanpenner** [comment]
it is: https://github.com/babel/ember-cli-babel/blob/master/package.json#L27

**Comment by gordonkristan** [comment]
@stefanpenner That's the dependency checker. The version checker is in the normal dependencies.

**Comment by stefanpenner** [comment]
ah, my bad. That looks like a mistake.

@gordonkristan got time to roll-out the fix?

I'm going to cut another ember-cli this morning, would love to squeeze this in.

**Comment by gordonkristan** [comment]
Yeah, I can do that. Give me like 20 minutes or so.

**Comment by gordonkristan** [comment]
Done. Bumped the version to 4.3.1 and published to NPM. Should be good to go.

**Comment by stefanpenner** [comment]
this actually was incorrect, this needs to stay around.

@QuantumInformation i need to understand your issue better, nothing seems to be wrong onthis side.

**Comment by QuantumInformation** [comment]
I'll try it out again manually, I was using a script to upgrade.

On Tuesday, 24 March 2015, Stefan Penner <notifications@github.com> wrote:

> this actually was incorrect, this needs to stay around.
>
> @QuantumInformation <https://github.com/QuantumInformation> i need to
> understand your issue better, nothing seems to be wrong onthis side.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/ember-cli-babel/issues/32#issuecomment-85597343>
> .
>


-- 

Kind regards
Nikos

**Comment by stefanpenner** [comment]
@QuantumInformation my guess is that NPM failed to install all the dependencies.

**Comment by blimmer** [comment]
I'm running into this same problem. Do I need to pump my version in my Ember-CLI-generated package.json?

**Comment by stefanpenner** [comment]
> I'm running into this same problem. Do I need to bump my version in my Ember-CLI-generated package.json?

I don't know which version you have, but the most recent version should be working correctly

**Comment by blimmer** [comment]
Bumping to 4.3.3 like this worked:
```
"ember-cli-babel": "^4.3.3",
```

Do the CLI deps need to also be updated? My ember-cli-babel version was pegged to `^4.0.0` in my generated package.json so this was breaking ember-cli 0.2.0 and 0.2.1.

**Comment by stefanpenner** [comment]
> ^4.0.0

is valid, npm should choose the best possible `4.x.x`

which npm version do you have?

**Comment by blimmer** [comment]
```
› ember --version
The package `ember-data` is not a properly formatted package, we have used a fallback lookup to resolve it at `/Users/blimmer/code/cli/Ibotta-Web/node_modules/ember-data`. This is generally caused by an addon not having a `main` entry point (or `index.js`).
version: 0.2.1
0.2.1

node: 0.12.1
npm: 2.7.3
```

**Comment by stefanpenner** [comment]
@blimmer i think you are seeing a problem but related to the broken solution to this issue, which has now been resolved.

I don't actually think this the reported issue is a bug in ember-cli-babel, but lets let @QuantumInformation confirm.

**Comment by blimmer** [comment]
Clearing npm cache fixed this for me.
```
ember-cli-babel@4.3.3 node_modules/ember-cli-babel
├── ember-cli-version-checker@1.0.2 (semver@4.3.1)
├── broccoli-filter@0.1.12 (broccoli-writer@0.1.1, promise-map-series@0.2.1, walk-sync@0.1.3, mkdirp@0.3.5, broccoli-kitchen-sink-helpers@0.2.6, quick-temp@0.1.2, rsvp@3.0.17)
└── broccoli-babel-transpiler@4.0.1 (clone@0.2.0, babel-core@4.7.16)
```

Thanks for fixing this quickly!

**Comment by QuantumInformation** [comment]
This is my script:

```
npm uninstall -g ember-cli
npm cache clean
bower cache clean
npm install -g ember-cli@0.2.1
rm -rf node_modules bower_components dist tmp
ember install:npm ember-cli@0.2.1
ember install
ember init
```

**Comment by QuantumInformation** [comment]
The error occurs on this line:

`ember install:npm ember-cli@0.2.1`

**Comment by stefanpenner** [comment]
your script is incorrect, it should be

```
npm uninstall -g ember-cli
npm cache clean
bower cache clean
npm install -g ember-cli@0.2.1
npm install --save-dev ember-cli@0.2.1
rm -rf node_modules bower_components dist tmp
npm install
ember init
```

**Comment by QuantumInformation** [comment]
oh, I copied mines from the steps here:

http://www.ember-cli.com/#upgrading-an-ember-cli-app

**Comment by QuantumInformation** [comment]
Actually I see some differences on http://www.ember-cli.com/#upgrading-an-ember-cli-app
, I'll try them and yours

**Comment by stefanpenner** [comment]
https://github.com/ember-cli/ember-cli/commit/e25d999014a5bcd8af00172d21e534c09e1703d5
