### ISSUE TITLE
 _EmberApplication is not defined in 7.14.1 build

### ISSUE THREAD

**Issue by jathanasiou** [babel/ember-cli-babel#322]
I just tried updating from ember-cli-babel in my app from `7.13.2` > `7.14.1` and this appears to be breaking my app's  distributable after building.

I am getting 
```
ReferenceError: _EmberApplication is not defined
```
in my console when running the app from a test environment. Runs from `ember serve` livereload appear to not be affected at all.

This happens when this change is the only one between deployments. My installed packages from `package.json` are seen below.

I've already tried nuking `node_modules` for a clean installation and it had no impact.

```json
{
  "scripts": {
    "build": "ember build",
    "lint:hbs": "ember-template-lint .",
    "lint:js": "eslint .",
    "start": "ember serve",
    "test": "ember test",
    "publish": "ember build --environment=production",
    "postpublish": "yarn bestzip dist.zip .ebextensions dist/"
  },
  "devDependencies": {
    "@ember/optional-features": "^1.3.0",
    "@fortawesome/ember-fontawesome": "^0.2.1",
    "@fortawesome/free-brands-svg-icons": "^5.12.0",
    "@fortawesome/free-solid-svg-icons": "^5.12.0",
    "bestzip": "^2.1.5",
    "bootstrap": "^4.4.1",
    "broccoli-asset-rev": "^3.0.0",
    "ember-auto-import": "^1.5.3",
    "ember-bootstrap": "^3.1.1",
    "ember-cli-app-version": "^3.2.0",
    "ember-cli-babel": "7.14.1",
    "ember-cli-cjs-transform": "^2.0.0",
    "ember-cli-dependency-checker": "^3.2.0",
    "ember-cli-deploy": "^1.0.2",
    "ember-cli-deploy-build": "^2.0.0",
    "ember-cli-deploy-compress": "^0.3.2",
    "ember-cli-deploy-gzip": "^1.0.1",
    "ember-cli-eslint": "^5.1.0",
    "ember-cli-htmlbars": "^4.2.2",
    "ember-cli-inject-live-reload": "^2.0.2",
    "ember-cli-sass": "^10.0.1",
    "ember-cli-sri": "^2.1.1",
    "ember-cli-template-lint": "^2.0.0",
    "ember-cli-uglify": "^3.0.0",
    "ember-concurrency": "^1.1.5",
    "ember-cookies": "^0.5.2",
    "ember-export-application-global": "^2.0.1",
    "ember-g-recaptcha": "^1.2.0",
    "ember-intl": "^4.2.3",
    "ember-load-initializers": "^2.1.1",
    "ember-local-storage": "^1.7.1",
    "ember-metrics": "^0.14.0",
    "ember-qunit": "^3.4.1",
    "ember-resolver": "^7.0.0",
    "ember-router-scroll": "^2.0.0",
    "ember-search-helper": "^2.0.0",
    "ember-simple-auth": "^2.1.1",
    "ember-source": "^3.16.0",
    "ember-truth-helpers": "^2.1.0",
    "eslint": "^6.8.0",
    "eslint-plugin-ember": "^7.7.2",
    "loader.js": "^4.7.0",
    "qunit-dom": "^0.9.2",
    "sass": "^1.25.1-test.1"
  },
  "dependencies": {
    "big.js": "^5.2.2",
    "dayjs": "^1.8.19",
    "ember": "^1.0.3",
    "ember-cli": "^3.15.2",
    "query-string": "^6.10.1"
  }
}

**Comment by rwjblue** [comment]
This issue is almost certainly due to https://github.com/ember-cli/babel-plugin-ember-modules-api-polyfill/issues/64. Please confirm you have `config/targets.js` defined (and that IE11 is the minimum).

**Comment by jathanasiou** [comment]
@rwjblue I do indeed have IE as a target for CI/Production builds so yeah that definitely explains it.
```javascript
// config/targets.js
const browsers = [
  'last 2 Chrome versions',
  'last 2 Firefox versions',
  'last 2 Safari versions',
];

const isCI = !!process.env.CI;
const isProduction = process.env.EMBER_ENV === 'production';

if (isCI || isProduction) {
  browsers.push('last 1 ie versions');
  browsers.push('>2% in GB');
}

module.exports = {
  browsers
};
```

Is there a workaround for this until the polyfill issue is resolved? Apart from removing IE11 target and/or sticking to `"ember-cli-babel": "7.13.2"`.

**Comment by rwjblue** [comment]
Sorry, I was saying that the oldest browser would be IE11 (and that IE11 itself was fine).

I just commented on the related issue with a link to what the correct fix is (@runspired fixed _basically_ the same bug in his recent work on the ember-data modules polyfill). Ideally, someone can port that fix over to babel-plugin-ember-modules-api-polyfill and we would have no issue...

**Comment by BnitoBzh** [comment]
If i understand correctly, the `babel-plugin-ember-modules-api-polyfill` is not already fixed to solve this problem ? It must have the same fix as the `babel-plugin-ember-data-packages-polyfill` module ?

**Comment by rwjblue** [comment]
Yes, and I linked to it from the issue above

**Comment by Robertodude** [comment]
I'm getting this exact error message today with _EmberApplication being undefined, not exactly sure what's triggered it...

`'use strict';

const browsers = [
  'last 1 Chrome versions',
  'last 1 Firefox versions',
  'last 1 Safari versions'
];

const isCI = !!process.env.CI;
const isProduction = process.env.EMBER_ENV === 'production';

if (isCI || isProduction) {
  browsers.push('ie 11');
}

module.exports = {
  browsers
};
`

**Comment by mallonenogueira** [comment]
@Robertodude Solved? I have the same problem.

**Comment by km-smith** [comment]
Ran into this today after bumping to ember-cli-babel@7.20.0. Pinning it back to 7.19.0 resolved the issue for now. I attempted to mess with config/targets.js (which my app didn't have that file to start) but even using "last 1 Chrome versions" as the only value in browsers didn't resolve the issue.

**Comment by rwjblue** [comment]
Would someone mind making a demo repo that I can check out?

**Comment by rbitting** [comment]
I had this same issue this morning and was able to solve it by deleting node modules and doing a fresh yarn install. Not sure if that was just luck, but figured I'd pass along

**Comment by rwjblue** [comment]
Seems related to https://babeljs.io/blog/2020/05/25/7.10.0 release. 🤔

**Comment by mallonenogueira** [comment]
Demo repository https://github.com/mallonenogueira/demo-project-_EmberApplication-error

**Comment by runspired** [comment]
@rwjblue isn't this likely the same issue as https://github.com/ember-cli/babel-plugin-ember-modules-api-polyfill/issues/64

**Comment by rwjblue** [comment]
@runspired - Yes, that is precisely what I said just above.

**Comment by rwjblue** [comment]
The point I made earlier today, is that I believe the Babel 7.10.0 release made Babel more correctly print out identifiers.

**Comment by jschmied** [comment]
Same error now:

ReferenceError: _EmberRSVP is not defined
    at Module.callback (http://localhost:4100/msa3/assets/vendor.js:99939:17)
    at Module.exports (http://localhost:4100/msa3/assets/vendor.js:111:32)
    at Module._reify (http://localhost:4100/msa3/assets/vendor.js:148:59)
    at Module.reify (http://localhost:4100/msa3/assets/vendor.js:135:27)
    at Module.exports (http://localhost:4100/msa3/assets/vendor.js:109:10)
    at requireModule (http://localhost:4100/msa3/assets/vendor.js:32:18)
    at Class._extractDefaultExport (http://localhost:4100/msa3/assets/vendor.js:106130:20)

Would be nice to have some workaround.

**Comment by rwjblue** [comment]
ember-cli-babel@7.20.1 was just released, and should fix the underlying issue.

https://github.com/babel/ember-cli-babel/releases/tag/v7.20.1

**Comment by vishusharmagit** [comment]
Upgrading ember version also fix the issue.
Our team upgraded following dependencies version to fix :
"ember-cli"
"ember-data"
"ember-source"
