### ISSUE TITLE
Cannot find module 'ember-cli-version-checker'

### ISSUE THREAD

**Issue by ro-ka** [babel/ember-cli-babel#33]
When running my Ember-CLI project in our Drone.io CI, I get the following warning:

```
Cannot find module 'ember-cli-version-checker'
```

This occurs just since like half an hour and seems to be related to the latest Commit (https://github.com/babel/ember-cli-babel/commit/add7944e3a9afb384cecdd8e528af3bfb3ee92ab).

Please revert.

**Comment by stefanpenner** [comment]
no lets not revert, but rather fix the issue.

**Comment by stefanpenner** [comment]
new version released.

**Comment by stefanpenner** [comment]
going to look into https://github.com/babel/ember-cli-babel/issues/32 when the submitter provides a response.

**Comment by ro-ka** [comment]
Thanks!

**Comment by gordonkristan** [comment]
@stefanpenner I think you moved the wrong package. You moved `ember-cli-dependency-checker` not `ember-cli-version-checker`.

**Comment by stefanpenner** [comment]
haha
fixing

**Comment by stefanpenner** [comment]
fixed
