### ISSUE TITLE
`babel plugins` to run after ember-cli-babel transpile

### ISSUE THREAD

**Issue by vothaison** [babel/ember-cli-babel#333]
Any babel plugins can only run before  ember-cli-babel transpile happens.
How can I let plugins run after ember-cli-babel transpile?
Thanks.

**Comment by rwjblue** [comment]
Ordering of babel plugins is somewhat tricky (since most of the time Babel merges them into a single pass), but you _can_ add plugins to be ordered after the ones automatically added by using `postTransformPlugins`. I would gladly accept a PR adding that info to the README...

```js
// ember-cli-build.js
let app = new EmberApp(defaults, {
  babel: {
    plugins: [/* these are prepended to the list of plugins that will be ran normally */],
    postTransformPlugins: [ /* these are appended to the normal list */],
  }
});
```

**Comment by rwjblue** [comment]
Closing for now (as I think ^ is the best we can do for now), happy to reopen if I've misunderstood something.

**Comment by vothaison** [comment]
Hi @rwjblue 

Thanks for the hint on `postTransformPlugins`.
And sorry I didn't state my actual issue clearly.
What I wish to do is to take the transpiled content of Ember CLI build and feed it to my custom plugin, so that I can add more code to it.

For instance
Here is the source file
```
/**
    Make table header for the action column
*/
export default Ember.Component.extend({ 
    reset: false,
});
```
(and, yes, global namespacing still is a thing in our projects)

Here is what comes out of Ember CLI build
```
;define("app/components/actions-header", ["exports"], function (_exports) {
  "use strict";

  Object.defineProperty(_exports, "__esModule", {
    value: true
  });
  _exports.default = void 0;

  /**
      Make table header for the action column
  */
  var _default = Ember.Component.extend({
    reset: false
  });

  _exports.default = _default;
});
```

I want to feed that code to my custom plugin so that I can immediately require() the module; i.e I want the module callback function to run immediately after define();
```
;define("app/components/actions-header", ["exports"], function (_exports) {
  "use strict";

  Object.defineProperty(_exports, "__esModule", {
    value: true
  });
  _exports.default = void 0;

  /**
      Make table header for the action column
  */
  var _default = Ember.Component.extend({
    reset: false
  });

  _exports.default = _default;
});
require("app/components/actions-header");
```

I have tried `postTransformPlugins`. But the plugin still runs before Ember CLI build . Which means I can't add more code outside of `define()`.

Thanks and Regards.

**Comment by rwjblue** [comment]
I see. I don't think babel is the right tool for that TBH. I would probably use the resulting dist tree and modify it as needed after compilation.

```js
// ember-cli-build.js

let app = new EmberApp(defaults, {});
let mainDist = app.toTree();

return new MyCustomPlugin(mainDist); // <-- do your special sauce here
```
