### ISSUE TITLE
is throwUnlessParallelizable a valid option?

### ISSUE THREAD

**Issue by jmonster** [babel/ember-cli-babel#336]
`throwUnlessParallelizable` is referenced in the README, but it's not included in the formal list of options. Was it removed? Was there a reason?

---

Given this command my build fails:

```fish
env THROW_UNLESS_PARALLELIZABLE=1 ember serve
```

However, when attempting to use the configuration approach instead,

```js
let app = new EmberApp(defaults, {
  'ember-cli-babel': {
    throwUnlessParallelizable: true
  }
});
```

parallelization silently fails (as it always has). This tells me that `throwUnlessParallelizable: true` **is not doing anything**?

**Comment by rwjblue** [comment]
The `ember-cli-build` option is only specifying that _your_ `ember-cli-babel` is parallelizable, not that **all** of them are.

The environment variable works by instructing **all** `ember-cli-babel` instances to put themselves in parallelize mode (or throw).
