### ISSUE TITLE
Yet Another _Ember is undefined error

### ISSUE THREAD

**Issue by cah-timhuddle** [babel/ember-cli-babel#349]
Before opening this i removed `node_modules` and `yarn.lock` so the environment was as clean as possible, just to confirm it was still an issue.

```
yarn why ember-cli-babel | grep @7                         
=> Found "ember-cli-babel@7.20.5"
=> Found "<internal-module>#ember-power-select#ember-cli-babel@7.20.5"
=> Found "ember-paper#ember-power-select#ember-cli-babel@7.20.5"
=> Found "<internal-module-2>#ember-text-measurer#ember-cli-babel@7.20.5"
=> Found "ember-paper#ember-text-measurer#ember-cli-babel@7.20.5"
=> Found "ember-power-datepicker#ember-power-calendar#ember-cli-babel@7.20.5"
=> Found "<internal-module-2>#ember-concurrency#ember-cli-babel@7.20.5"
=> Found "ember-paper#ember-concurrency#ember-cli-babel@7.20.5"
```

```
yarn why babel-plugin-ember-modules-api-polyfill | grep @2 
=> Found "babel-plugin-ember-modules-api-polyfill@2.13.4"
=> Found "ember-data#ember-cli-babel#babel-plugin-ember-modules-api-polyfill@2.13.4"
```

Still getting `Uncaught ReferenceError: _Ember is not defined`

From the stack, it looks to be coming out of `ember-concurrency`

Pre-transpiled
```
state: computed('isDropped', 'isCanceling', 'hasStarted', 'isFinished', function() {
    if (get(this, 'isDropped')) {
      return 'dropped';
    } else if (get(this, 'isCanceling')) {
      return 'canceled';
    } else if (get(this, 'isFinished')) {
      return 'finished';
    } else if (get(this, 'hasStarted')) {
      return 'running';
    } else {
      return 'waiting';
    }
  }),
```

Transpiled
```
state: (_Ember = Ember).computed.apply('isDropped', 'isCanceling', 'hasStarted', 'isFinished', function () {
      if (Ember.get(this, 'isDropped')) {
        return 'dropped';
      } else if (Ember.get(this, 'isCanceling')) {
        return 'canceled';
      } else if (Ember.get(this, 'isFinished')) {
        return 'finished';
      } else if (Ember.get(this, 'hasStarted')) {
        return 'running';
      } else {
        return 'waiting';
      }
    }),
```

**Comment by rwjblue** [comment]
This looks like **exactly** the thing that was fixed by 7.20.5 (via babel-plugin-ember-modules-api-polyfill@2.13.4).

@cah-timhuddle:

* Can you `rm -rf node_modules && yarn`, then double check the transpiled results? (this is to try and ensure we aren't using a pre-cached transpilation result from a prior ember-cli-babel version)
* Can you identify if there any _other_ `computed` usages in this file? If so, what do they look like?

**Comment by cah-timhuddle** [comment]
So, to be specific this file is [here](https://github.com/machty/ember-concurrency/blob/master/addon/-task-instance.js#L210) (I have nothing to do w/ `ember-concurrency`, we just use it). Looks like there's a couple other `computed`s in there like `isDropped` and a few others that aren't dependencies of `state`

After running `rm -rf node_modules && yarn`, the output from the two `yarn why` commands was identical.

Ran a `yarn build` instead of `yarn start` this time, just to make it easier to look at the transpiled output.

All of the output looks just like reported above.

**Comment by cah-timhuddle** [comment]
Huh, so i tried to make the smallest possible repro, and when i go looking at that compiled code, it appears to be fixed. So its something weird in our repo (which is private and so cannot be shared). 

FWIW, we're on Ember 3.0.4, but this would appear to actually indeed be "fixed" in a sane environment.

**Comment by rwjblue** [comment]
@cah-timhuddle - Are there any ember-cli-babel@6.x instances in use (anything over ember-cli-babel@6.9.0 would get the "bad" babel-plugin-ember-modules-api-polyfill versions)?

**Comment by cah-timhuddle** [comment]
Hoo boy, there's a whole bunch of 6.18.0's (like 30+) and also a few 5.2.8's.

**Comment by rwjblue** [comment]
You should be able to ensure that ember-data@3.2.0 gets the fixed version of babel-plugin-ember-modules-api-polyfill.

**Comment by rwjblue** [comment]
I think this is fixed now (for a while), closing...
