### ISSUE TITLE
Move non-standard syntax behind flag

### ISSUE THREAD

**Issue by joliss** [babel/ember-cli-babel#35]
At the moment, we treat `<foo />` as valid JavaScript and transpile it into `React.createElement("foo", null);`. This happens with Babel 4.7.16 as well as the 5.0.0-beta3.

We should probably disable all non-standard syntax, as well syntax that is too early in the standardization process to be considered stable for our purposes. Perhaps we can add flags, so that people can opt-in if they want to test-drive experimental syntax.

**Comment by stefanpenner** [comment]
this seems like a babel concern

**Comment by stefanpenner** [comment]
> We should probably disable all non-standard syntax, as well syntax that is too early in the standardization process to be considered stable for our purposes. Perhaps we can add flags, so that people can opt-in if they want to test-drive experimental syntax.

this would be a good default for babel

**Comment by stefanpenner** [comment]
Sebastian McKenzie [12:35 PM] 
in 5.0.0 you'll be able to set a `nonStandard` option to `false`

**Comment by sebmck** [comment]
> as well syntax that is too early in the standardization process to be considered stable for our purposes

This is already disabled by default. JSX and Flow is the exception.

**Comment by stefanpenner** [comment]
`nonStandard: false``

**Comment by stefanpenner** [comment]
done
