### ISSUE TITLE
Build Error (broccoli-persistent-filter:EslintValidationFilter)

### ISSUE THREAD

**Issue by k238459** [babel/ember-cli-babel#360]
Using Ember cli 3.19 and using ember cli babel 7.20.5.

Doesnt allow me to build 
Build Error (broccoli-persistent-filter:EslintValidationFilter) in < a file name in my workspace)
Cannot read property 'range' of null

**Comment by rwjblue** [comment]
Hmm, I'm not sure what you mean here. Can you make a demo repo that we can use to help you debug?
