### ISSUE TITLE
Upgrading from 7.23.1 to 7.24.0 breaks various NPM module imports

### ISSUE THREAD

**Issue by kpfefferle** [babel/ember-cli-babel#386]
I am unable to upgrade some of my projects to ember-cli-babel@7.24.0 because it breaks importing from some NPM modules. So far I have seen this issue with the following packages:

- [Faker](https://github.com/marak/Faker.js/): `import faker from 'faker';`
- [Luxon](https://moment.github.io/luxon/): `import { DateTime } from 'luxon';`

Both of these worked fine in my Ember projects up through ember-cli-babel@7.23.1, but with ember-cli-babel@7.24.0 they error out with `Error: Could not find module [MODULE] imported from [FILE]`

**Comment by rwjblue** [comment]
Can you make a small repro?

**Comment by kpfefferle** [comment]
My initial attempt to make a [small repro](https://github.com/kpfefferle/ember-cli-babel-package-imports) using only these addons is not generating the same errors I was seeing in my other application. I'll close this for now while I investigate what else might be causing this, and I'll reopen later if needed.

**Comment by rwjblue** [comment]
kk, thank you for reporting back! Please do let me know if you are able to track down a repro, I definitely want to make sure we aren't breaking things for folks...
