### ISSUE TITLE
`for of` loop is breaking in IE9

### ISSUE THREAD

**Issue by mgenev** [babel/ember-cli-babel#39]
Saying `Symbol 'undefined'` when used. 
Per talking with @sebmck, it turns out it needs the polyfill http://babeljs.io/docs/usage/polyfill/

Does this mean that ember-cli-babel is not including it and it has to?

**Comment by gordonkristan** [comment]
> Does this mean that ember-cli-babel is not including it and it has to?

You're correct in that it's not including the polyfill. It's on the roadmap (#24), but it's not finished yet. Until it is, you'll have to include the polyfill yourself.
