### ISSUE TITLE
How to include polyfill?

### ISSUE THREAD

**Issue by miguelmota** [babel/ember-cli-babel#40]
I'm trying to use `Symbol` and the [babel page](https://babeljs.io/docs/learn-es6/) says I need to include the [polyfill](http://babeljs.io/docs/usage/polyfill/)

What is the best approach to include the polyfill in an ember cli project?

**Comment by gordonkristan** [comment]
Until #24 is finished, I would just treat it as an external dependency. Add it to your `vendor` folder and put this in your Brocfile.

```js
app.import('vendor/babel-polyfill.js', { prepend: true });
```

**Comment by alexlafroscia** [comment]
You can also include the polyfill through Bower and import it from your Bower dependencies, if you want to avoid actually having it in your repo.  You can find the package that I used [here](https://github.com/nicksrandall/babel-polyfill).https://github.com/nicksrandall/babel-polyfill

**Comment by miguelmota** [comment]
Cool thanks guys!

**Comment by BrianSipple** [comment]
I've noticed that this is the first thing shown by Google when you search "ember babel polyfill". For any any of those folks looking for an answer, please set the `includePolyfill` property of the `babel` hash in your `ember-cli-build.js` file to `true`: 

```js
var app = new EmberApp({
  babel: {
    includePolyfill: true
  }
});
```

**Comment by iNaD** [comment]
For further reference if someone will find this Issue. With BrianSipple's solution you will get a deprecation warning with current versions `DEPRECATION: Putting the "includePolyfill" option in "babel" is deprecated, please put it in "ember-cli-babel" instead.`

So the correct solution for newer versions is:
```js
var app = new EmberApp({
  'ember-cli-babel': {
    includePolyfill: true
  }
});
```

**Comment by gabrielgrant** [comment]
This still ranks high on Google for `ember polyfill`. For anyone finding this in 2020, this is no longer needed, Ember now has built-in support for targeting exactly which browsers you want: https://guides.emberjs.com/release/configuring-ember/build-targets/
