### ISSUE TITLE
Removal of modules polyfill for ember-source 3.27+ breaks production builds for all apps using registerWaiter

### ISSUE THREAD

**Issue by runspired** [babel/ember-cli-babel#406]
Offending imports:

```ts
import { registerWaiter, unregisterWaiter } from '@ember/test';
```

These imports are missing in non-test env production builds leading the build to break. This includes all versions of EmberData, meaning that a large share of [apps running ember-source 3.27 are unable to ship to production](https://github.com/emberjs/ember.js/issues/19538)

I believe this worked prior to 3.27 because the transformation of `registerWaiter` to `Ember.registerWaiter` meant no import was present, and therefore `registerWaiter` being undefined did not break anything as apps typically wrap usage of it in `if (DEBUG) {}` or `if (Ember.testing) {}`.

**Comment by runspired** [comment]
The source of the error is this build step here: https://github.com/emberjs/ember.js/blob/master/lib/index.js#L225-L228

Which filters all `ember-testing` paths out of the build. `@ember/test` remains in the build but when accessed will fail because it re-exports from `ember-testing` https://github.com/emberjs/ember.js/blob/master/packages/%40ember/test/index.js#L1-L11

**Comment by rwjblue** [comment]
I think this was fixed by https://github.com/emberjs/ember.js/pull/19540, but happy to reopen if that is incorrect.
