### ISSUE TITLE
7.26.6 still transpiling to use Ember global

### ISSUE THREAD

**Issue by alexlafroscia** [babel/ember-cli-babel#408]
Hello! I've been trying to upgrade our app to Ember 3.27 for a few days but keep running into errors about using the `Ember` global.

I am using Yarn resolutions to ensure that _only_ `ember-cli-babel@7.26.6` is installed, even for addons that are using out-of-date versions of that package (I checked each addon individually to see if they did any custom Babel stuff, and none of them do, so this seems... safe enough?). This has been working fine up until Ember 3.27.

Now, I am getting errors related to the Ember global being used. For example, this line of code from Ember Data:

https://github.com/emberjs/data/blob/master/packages/store/addon/-private/system/promise-proxies.js#L44

ends up transpiled into `Ember.computed.reads` which, apparently, is no longer a function at all, causing an exception to be thrown.

My understanding is that `ember-cli-babel@7.26.6`, when used with Ember 3.27, should not transpile code to use the Ember global. Is there some way I can hunt down why this is not behaving that way?

**Comment by rwjblue** [comment]
Please double check to ensure you are on the latest version of ember-data. Specifically you need https://github.com/emberjs/data/pull/7527 which was back ported in https://github.com/emberjs/data/pull/7552 and released in 3.27.1 (released yesterday).

**Comment by alexlafroscia** [comment]
Yup, that did it! Thanks @rwjblue and @runspired 😀
