### ISSUE TITLE
Babel 5.3.0

### ISSUE THREAD

**Issue by stavarotti** [babel/ember-cli-babel#41]
Looks like Babel 5.3.0 has some pretty significant speed improvements.  Any chance of bumping the version to 5.3.0?  See https://twitter.com/babeljs/status/598303570824421376.

**Comment by gordonkristan** [comment]
This plugin actually relies on the [broccoli-babel-transpiler](https://github.com/babel/broccoli-babel-transpiler) plugin to do the actual transpilation. Luckily, they use a caret dependency version for babel-core (`^5.0.0`), so it'll use the highest `5.x.x` version available. If you wipe your `node_modules` directory and reinstall, you'll see that it's using version `5.4.2`. You can check in this file:

```
node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/package.json
```

I imagine that we won't bump the major version of this plugin until a `6.x.x` release of Babel.

**Comment by stefanpenner** [comment]
Ya confirmed.

**Comment by stavarotti** [comment]
Confirmed after clearing npm cache.  Thanks.
