### ISSUE TITLE
Class decorator woes with 7.26.7

### ISSUE THREAD

**Issue by jherdman** [babel/ember-cli-babel#423]
Since updating to ecli-babel 7.26.7 I see the following error:

> Decorating class property failed. Please ensure that proposal-class-properties is enabled and runs after the decorators transform

This is reproduced with the following app: https://github.com/jherdman/hump-day-sadness

Edit: updated the version number 🤭

**Comment by vst** [comment]
Same here. I had to pin down the dependency to v7.26.6.

PS: I think that you meant v7.26.7.

**Comment by NullVoxPopuli** [comment]
Whoops, i made a duplicate https://github.com/babel/ember-cli-babel/issues/425

**Comment by dknutsen** [comment]
@vst you can use a yarn resolution to force 7.26.6 temporarily

**Comment by chriskrycho** [comment]
Working on a fix in #426. Will update there as we make progress. (Turns out we didn't have test coverage for this! That's the first thing I'm doing: adding coverage.)
