### ISSUE TITLE
Babel polyfill broken in 7.26.10

### ISSUE THREAD

**Issue by nickschot** [babel/ember-cli-babel#429]
Specifying 

```
  // ember-cli-build.js
  let app = new EmberApp(defaults, {
    'ember-cli-babel': {
      includePolyfill: true,
    },
  });
```
will cause the following error on build:
```
Build Error (SourceMapConcat)

ENOENT: no such file or directory, open '/var/folders/7h/82hn6hyn1bngg96_xvhlmq040000gn/T/broccoli-34311LQfVtgUc1OgD/out-262-broccoli_debug_debug_5_vendor_js/vendor/babel-polyfill/polyfill.js'
```

Minimal reproduction: https://github.com/nickschot/babel-polyfill-repro

**Comment by Adonis320** [comment]
Affects versions 7.26.7 and upwards

**Comment by rwjblue** [comment]
Hmph. Why? This is strange, we didn't change anything RE: the polypill in these versions 🤔

**Comment by nickschot** [comment]
Good question 😂 I ran into it testing the updated version to see if my private class property issues were resolved.

**Comment by chriskrycho** [comment]
I suspect it was an “unclean revert”[^1]: ea752c4 reverted 0d47e8b, but did *not* revert the bump to `@babel/preset-env` that [was included](https://github.com/babel/ember-cli-babel/commit/0d47e8be96b93120b0bcb261dd719231e73ef2d0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519) there. Presumably there’s a difference in what the updated `@babel/preset-env` is requiring *or not* for the polyfill.

[^1]: this sounds hilarious 😂

**Comment by rwjblue** [comment]
Sorry about this y'all, fixed in https://github.com/babel/ember-cli-babel/releases/tag/v7.26.11
