### ISSUE TITLE
Source Maps?

### ISSUE THREAD

**Issue by tp** [babel/ember-cli-babel#43]
When debugging scripts transpiled by "ember-cli-babel" 5.0.0, I see no Source Maps in Chrome.

Is there a hidden flag one must enable?

(Sorry for asking here, but I couldn't find anything related to this).

**Comment by stefanpenner** [comment]
they are disable because esperanto does not merge them. We will be moving all of our ES6 transpilation modules included to use babel, which will resolve this issue.

**Comment by tp** [comment]
Ok, thanks for the update. Looking forward to the fix. Thanks for all your work :+1:

**Comment by stefanpenner** [comment]
Thanks. Closing this, as it isn't really an issue with this addon. Rather the larger build pipeline in ember.

Not to worry though, it's pretty high priority for me. It won't be forgotten.
