### ISSUE TITLE
New version of broccoli-babel-transpiler breaks live reloading in ember cli

### ISSUE THREAD

**Issue by ryanhollister** [babel/ember-cli-babel#45]
I noticed that a fresh install of ember-cli no longer correctly re-compiles on file change. I have tracked this down to a change in broccoli-babel-transpiler. It appears that the change from broccoli-babel-transpiler@5.0.0 to broccoli-babel-transpiler@5.2.3 is the problem. Reverting to broccoli-babel-transpiler@5.0.0 fixes my issues.

**Comment by stefanpenner** [comment]
Strange. Will take a look after lunch

**Comment by herbrandson** [comment]
Any progress on this one?

**Comment by stefanpenner** [comment]
I was unable to reproduce. Can someone provide a repo that demonstrates this?

**Comment by stefanpenner** [comment]
this seems to have gone stale, if someone can provide a reproduction I will take a look and reopen.
