### ISSUE TITLE
[QUEST] v8 Release

### ISSUE THREAD

**Issue by bertdeblock** [babel/ember-cli-babel#453]
- [x] Move `@babel/core` to `peerDependencies` - https://github.com/babel/ember-cli-babel/pull/452
- [x] Drop support for Node v6, v8, v10 and v12 (Add support for Node v14, v16 and v18) - https://github.com/babel/ember-cli-babel/pull/454
- [x] Remove `includePolyfill` support - https://github.com/babel/ember-cli-babel/pull/458
- [x] Change `broccoli-babel-transpiler` to either make `@babel/core` a peer dependency or make it accept the current Babel as an argument, and upgrade `ember-cli-babel` to that version (without this we're still not actually transpiling people's code with the version of `@babel/core` in their own `package.json`) - https://github.com/babel/broccoli-babel-transpiler/pull/221
- [x] Update `broccoli-babel-transpiler` to v8 - https://github.com/babel/ember-cli-babel/pull/460
- [x] Write upgrade guide for apps and addons - https://github.com/babel/ember-cli-babel/pull/464
- [x] Release first v8 beta version
- [x] Release a stable version of `broccoli-babel-transpiler` v8 and update in `ember-cli-babel` - https://github.com/babel/ember-cli-babel/pull/494
- [x] Release a stable version of `ember-cli-babel` v8
- [x] Update `ember-cli-babel` in the default blueprint and add `@babel/core` - https://github.com/ember-cli/ember-cli/pull/10141

**Comment by kategengler** [comment]
from @rwjblue in Discord
> rwjblue — 09/16/2022
Agree
There’s a non trivial amount of cleanup we should do though
Like bumping the broccoli-Babel-transpiler version
Changing poly fill support around (removing it basically)

**Comment by ef4** [comment]
Also just noticed that broccoli-babel-transpiler has `@babel/core` in `dependencies`. That means we should also change and release broccoli-babel-transpiler to either use a peerDep *or* accept babel itself as an argument when you create the broccoli node.

**Comment by ef4** [comment]
(I can't edit the description above, so I'm rewriting it here with updates.)

 - [ ] move `@babel/core` to peerDependencies https://github.com/babel/ember-cli-babel/pull/452
 - [ ] drop support for node < 14 and add test coverage for 14 through 18
 - [ ] remove `includePolyfill` support
 - [ ] change broccoli-babel-transpiler to either make `@babel/core` a peerDep or make it accept the current Babel as an argument, and upgrade ember-cli-babel to that version. (Without this we're *still* not actually transpiling people's code with the version of `@babel/core` in their own package.json.)

**Comment by bertdeblock** [comment]
@ef4 For the `broccoli-babel-transpiler` update, which option do you prefer / is best in this case?

**Comment by bertdeblock** [comment]
Also, does `includePolyfill` support need to be dropped without a replacement?

**Comment by bertdeblock** [comment]
Created PRs for the remaining issues. Hope I understood everything correctly 😄.

**Comment by ef4** [comment]
> Also, does includePolyfill support need to be dropped without a replacement?

babel has deprecated the polyfill and tells you the replacement is to add `import "core-js/stable"` yourself: https://babeljs.io/docs/en/babel-polyfill

This probably belongs in changelog and in any how-to-upgrade doc that we may write for this major release.

**Comment by rwjblue** [comment]
I released https://github.com/babel/broccoli-babel-transpiler/releases/tag/v8.0.0-beta.1 so we can start updating here a bit easier

**Comment by bertdeblock** [comment]
👍 I'll try to fix the `broccoli-babel-transpiler` update here asap.

**Comment by ef4** [comment]
We're going to need to document what addon authors are supposed to do. They traditionally must have ember-cli-babel in `dependencies` and therefore they bring their own babel into app builds. The way to reproduce that after this change is for addons to `@babel/core` in `dependencies`. But it's probably better for them to put it into `peerDependencies` (and `devDependencies`).

**Comment by bertdeblock** [comment]
After the transpiler PR, I can look into writing an upgrade guide for apps and addons.

**Comment by ef4** [comment]
I said about "it's probably better for them to put it into peerDependencies", but after thinking about it, the less disruptive change is to put `@babel/core` into dependencies. That is equivalent to how things already worked, with every addon potentially bringing its own babel. We don't need to rock that boat any harder, the longer-term plan is for them to get to v2 addons and then they don't bring ember-cli-babel at all.

**Comment by JackHowa** [comment]
Excited to see babel polyfills removed 👍

**Comment by bertdeblock** [comment]
v8 is released.

**Comment by ef4** [comment]
Thank you @bertdeblock!
