### ISSUE TITLE
Re-exporting a module compiles to 'exports.default = ...`

### ISSUE THREAD

**Issue by alexlafroscia** [babel/ember-cli-babel#49]
I've been doing some IE debugging and noticed a show-stopper that seems to fall into Babel's territory.  I keep getting the following issue:

> Expected Identifier

Which traces back to the following code:

```javascript
define('qualaris-mantra/components/ember-wormhole', ['exports', 'ember-wormhole/components/ember-wormhole'], function (exports, ember_wormhole) {

	'use strict';

	exports.default = ember_wormhole.default; // Error points to this line

});
```

I went and looked up the `ember-wormhole` code that corresponds to this module, and it can be found [here](https://github.com/yapplabs/ember-wormhole/blob/master/app/components/ember-wormhole.js#L1).  In case you don't feel like following the link, it's just re-exporting another module.

Is this an issue on Babel's end? To me, it seems like the problem is that Babel translates the re-export to

```javascript
exports.default = ember_wormhole.default;
```

instead of

```javascript
exports['default'] = ember_wormhole['default'];
```

I looked around at all the other modules and they all seem to use the `exports['default']` syntax.  It's only an issue with IE, and all the other modules seem to be OK.

***

This was originally opened as an issue as [an issue on Babel's repo](https://github.com/babel/babel/issues/2117) but we determined that it's probably not an issue with Babel's core. It think it's more likely that the problem is with the transformation the the CLI uses to handle modules instead.

**Comment by stefanpenner** [comment]
confusingly this is a bug in esperanto https://github.com/esperantojs/esperanto/pull/176

**Comment by alexlafroscia** [comment]
Huh, alright then! Thanks for the follow-up :smile:

**Comment by stefanpenner** [comment]
https://github.com/ember-cli/ember-cli/pull/4545 will fix it. I plan to release another ember-cli this afternoon.
