### ISSUE TITLE
broccoli-babel-transpiler branch doesn't exist

### ISSUE THREAD

**Issue by mattgrannary** [babel/ember-cli-babel#52]
Just ran into this issue when trying to reinstall my node_modules. The new revision added for broccoli-babel-transpiler has a typo in the name. Fails on install with error:

npm ERR! git rev-list -n1 broccoli-peristent-filter: fatal: ambiguous argument 'broccoli-peristent-filter': unknown revision or path not in the working tree.

Should be: babel/broccoli-babel-transpiler#broccoli-persistent-filter

Actual: babel/broccoli-babel-transpiler#broccoli-peristent-filter

Missing an 's' in persistent

**Comment by mattgrannary** [comment]
Or actually.. Looking at babel/broccoli-babel-transpiler repo and there is no revision/tag/branch for broccoli-peristent-filter. There is a 'persistent' branch, is that what was intended? broccoli-peristent-filter also fails to install.

**Comment by mattgrannary** [comment]
related to #53

**Comment by gordonkristan** [comment]
Fixed by #51. Hopefully #56 will be approved and we'll publish a new version ASAP.

**Comment by robclancy** [comment]
Awesome... this combined with npm being shit makes it way too easy for mistakes like this to completely stop or CI from working.
