### ISSUE TITLE
let issue

### ISSUE THREAD

**Issue by mnowik** [babel/ember-cli-babel#58]
I have an issue using let.

Here is my code:
```javascript
if (a === b ) {
  let defaultReturnAddress = {};
  let returnAddress = _this.get('currentUser.address');
  ...
}
if (defaultReturnAddress) {...}
```

Here is the translation using ember-cli-babel@5.1.5
```javascript
if (a === b ) {
  var _defaultReturnAddress = {};
  var returnAddress = _this.get('currentUser.address');
  ...
}
if (defaultReturnAddress) {...}
```

It seems to be linked to this error on babel https://github.com/babel/babel/issues/166.
This error was closed a while ago. however, it seems to be a Babel issue.

**Comment by stefanpenner** [comment]
If it's a babel issue. It's likely best to open it there. This library merely wraps whichever babel your npm installs

**Comment by mnowik** [comment]
Tks I will post it there.
