### ISSUE TITLE
Babel 6.0

### ISSUE THREAD

**Issue by stefanpenner** [babel/ember-cli-babel#62]
placeholder, document steps required once explored.

**Comment by Turbo87** [comment]
@topaxi do you want to take a look at upgrading this project too?

**Comment by topaxi** [comment]
Afaik, before we can do this, ember-build has some plugins which need to be ported to the babel6 API, i've looked into this some weeks ago. I didn't get ember-build running with babel6 because I haven't found proper babel5 to babel6 API migration docs.
Also I currently don't really have time to look into this, sorry :)

**Comment by Turbo87** [comment]
okay, thanks for the quick feedback though!

**Comment by knownasilya** [comment]
We need to upgrade to babel-core 6+ to avoid the minimatch vulnerability.

**Comment by Turbo87** [comment]
@knownasilya feel free to join the effort 😉

**Comment by Turbo87** [comment]
main task list is at https://github.com/ember-cli/ember-cli/issues/5015

**Comment by Turbo87** [comment]
> We need to upgrade to babel-core 6+ to avoid the minimatch vulnerability.

can you explain where exactly that vulnerability is and how it related to this project (or Ember)?

**Comment by stefanpenner** [comment]
> We need to upgrade to babel-core 6+ to avoid the minimatch vulnerability.

well that is basically not something we can "just bump"  if there is a babel-core 5x issue they need to do  maintenance release. Also, i suspect the vulnerable does not affect us, but would love to see.

**Comment by rwjblue** [comment]
Closed by https://github.com/babel/ember-cli-babel/pull/115.
