### ISSUE TITLE
Can't get polyfilled features to transpile

### ISSUE THREAD

**Issue by patocallaghan** [babel/ember-cli-babel#66]
OK this may be some stupidity on my part but I'm trying to try out the polyfilled features with the latest ember-cli but can't get it to work.

I have a sample repo here https://github.com/patocallaghan/test-app which has some [es6 polyfill-only code](https://github.com/patocallaghan/test-app/blob/master/app/app.js#L16).

```
Object.assign({}, { test: "test" });
"234234234".include("5");

var m = new Map();
m.set("hello", 42);
m.set(s, 34);
m.get(s) == 34;

function timeout(duration = 0) {
  return new Promise((resolve, reject) => {
    setTimeout(resolve, duration);
  });
}
```

I then have the `includePolyfill` flag set in [ember-cli-build.js](https://github.com/patocallaghan/test-app/blob/master/ember-cli-build.js#L8). Yet when the JS builds the code isn't transpiled

**test-app.js**
```
Object.assign({}, { test: "test" });
"234234234".include("5");

var m = new Map();
m.set("hello", 42);
m.set(s, 34);
m.get(s) == 34;

function timeout() {
  var duration = arguments.length <= 0 || arguments[0] === undefined ? 0 : arguments[0];

  return new Promise(function (resolve, reject) {
    setTimeout(resolve, duration);
  });
}
```

Running `ember -v` I get:
```
version: 1.13.13
node: 5.0.0
npm: 2.14.10
os: darwin x64
```

Am I missing something? Face-palm at the ready..

**Comment by rwjblue** [comment]
@patocallaghan - The point of the polyfill is that `Object.assign` is actually created.  I would not expect the transpiled output to be different.

**Comment by patocallaghan** [comment]
yep, I knew a facepalm would be warranted. I was thinking that the code would be transpiled into a different form similar to fat-arrows etc. Checking `vendor.js` it does indeed contains a polyfill for the above.
