### ISSUE TITLE
Support of .babelrc in host app?

### ISSUE THREAD

**Issue by trisrael** [babel/ember-cli-babel#68]
I'd like to make use of some of the [plugins](http://babeljs.io/docs/plugins/) - does the steps provided there work as prescribed with this addon (for the host app) ?

**Comment by Iftahh** [comment]
@trisrael did you have any luck using plugins? if so how?

**Comment by Turbo87** [comment]
@trisrael this Ember addon is currently still using Babel 5 and the page you linked describes the process for using Babel 6 plugins. There is an open issue on upgrading this project to Babel 6 (see #62), but this will most likely take a little more time.

**Comment by stefanpenner** [comment]
its also worth noting the babelrc stuff is most likely incompatible with `npm link` and potentially how add-ons work. I don't believe it works correctly with nested babelrc... If im right, we would need to fix that in babel land.

**Comment by Turbo87** [comment]
closing this in favor of #62
