### ISSUE TITLE
With async and await; TypeError: regeneratorRuntime.awrap is not a function

### ISSUE THREAD

**Issue by timbaas** [babel/ember-cli-babel#71]
I'm seeing "TypeError: regeneratorRuntime.awrap is not a function".

This happens when I try to use the 'async' and 'await' methods.

The packages I use are listed here:
https://gist.github.com/timbaas/8487e7df204dffa651a5effe3eda0450

**Comment by stefanpenner** [comment]
yes, you''ll need to include the runtime. https://github.com/babel/ember-cli-babel#polyfill

**Comment by timbaas** [comment]
Thanks for the quick reply stefan, unfortunately it does not seem to work for me, here's my app configuration:

`var app = new EmberApp({
    fingerprint: {
      enabled: isProductionLikeBuild,
      extensions: [ 'js', 'css', 'png', 'jpg', 'gif', 'map', 'pdf', 'eot', 'svg', 'ico', 'ttf', 'woff', 'woff2' ]
    },
    babel: {
      includePolyfill: true,
      comments: false
    },
    wrapInEval: false,
    tests: false,
    trees: {
      app:        mergeTrees(apps,      { overwrite: true } ),
      templates:  mergeTrees(templates, { overwrite: true } ),
      styles:     mergeTrees(styles,    { overwrite: true } )
    },
    minifyCSS:  { enabled: isProductionLikeBuild },
    minifyJS:   { enabled: false },
    sourcemaps: { enabled: false },
    storeConfigInMeta: false,
    sassOptions: {
      extension: 'scss' // or sass
    }
  });`

**Comment by remzr7** [comment]
@Turbo87 updates on this?

**Comment by Turbo87** [comment]
@remzr7 feel free to provide us with instructions to reproduce this issue, otherwise it seems very hard to fix this issue

**Comment by remzr7** [comment]
Ah, 

If I do not have   "@glimmer/web-component": "^0.1.0" in my package.json this issue occurs but it doesn't otherwise. Why doesn't the babel setting in ember-cli-build fix it?
