### ISSUE TITLE
EventEmitter memory leak error

### ISSUE THREAD

**Issue by knownasilya** [babel/ember-cli-babel#76]
Not sure if this is the place, or if `tmp` is responsible. See https://github.com/raszi/node-tmp/issues/85

Would be happy to give access to my app for anyone looking to debug.

**Comment by denchen** [comment]
I'm getting a very similar error. I'm using ember-cli 2.5.0 with ember-cli-babel 5.1.6. I've seen this on OSX with Node 4.4.5 and RedHat with Node 0.12.

Here's my error:


    % ember serve
    (node) warning: possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit.
    Trace
        at process.addListener (events.js:239:17)
        at Object.<anonymous> (/Users/denchen/dev/ops-ui/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/broccoli-merge-trees/node_modules/can-symlink/node_modules/tmp/lib/tmp.js:449:9)
        at Module._compile (module.js:409:26)
        at Object.Module._extensions..js (module.js:416:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)
        at Module.require (module.js:353:17)
        at require (internal/module.js:12:17)
        at Object.<anonymous> (/Users/denchen/dev/ops-ui/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/broccoli-merge-trees/node_modules/can-symlink/index.js:1:73)
        at Module._compile (module.js:409:26)
        at Object.Module._extensions..js (module.js:416:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)
        at Module.require (module.js:353:17)
        at require (internal/module.js:12:17)
       at Object.<anonymous> (/Users/denchen/dev/ops-ui/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/broccoli-merge-trees/index.js:9:18) 
    Environment: development
    Livereload server on http://localhost:49153
    Serving on http://localhost:3000/

    Build successful - 6821ms.

I'm not sure if it's an issue with a node_module or my code, and I'm not fluent enough in the world of Node to even begin to debug this.

**Comment by stefanpenner** [comment]
Seems related to tmp, unsure what we can do on our end.

**Comment by denchen** [comment]
Speaking of /tmp, I only just noticed that a lot of directories are left over. After cleaning out /tmp and then starting Ember, there are 1700+ directories. After stopping & starting Ember again, there are 3400+ directories. Is this normal that files aren't being cleaned up?

**Comment by stefanpenner** [comment]
@denchen they should be cleaned up

**Comment by stefanpenner** [comment]
> @denchen they should be cleaned up

Well, actually ones in system tmp are the result of persistent filters that do remain. `project/tmp` should be cleanedup

**Comment by denchen** [comment]
@stefanpenner Hmm, yeah, my `<project>/tmp` folder is not being cleaned up. For now, I'm `rm -rf tmp/` before each time I start Ember. Is there anything I can do to help narrow down the root cause?

**Comment by stefanpenner** [comment]
Make a reproduction and share it as an issue

**Comment by denchen** [comment]
https://github.com/denchen/test-app

I've tried to remove as much fluff as possible and still have the `/tmp` and EventEmitter issue. I could probably pare it down by removing even more packages if you so desire. Again, I'm seeing this with OSX + Node 4.4.5.

**Comment by stefanpenner** [comment]
@denchen thanks

**Comment by stefanpenner** [comment]
> still have the /tmp

doesn't sound like a problem, that is the persistent cache.

**Comment by stefanpenner** [comment]
node 5.x didn't seem to have the leak

**Comment by stefanpenner** [comment]
@denchen was able to provide me with an example.

The problem appears to be (still confirming):

* more then 10 dependencies try to do cleanup when the process exists
* for some reason the limit of 10 is set, and is likely far to low a default

**Comment by stefanpenner** [comment]
quick reproduction that also works on my machine..;

```js
var count = 0;

for (var i = 0; i < 11; i++) {
        process.addListener('exit', function() {
                        console.log('didExit', count++);
        });
}
```

**Comment by stefanpenner** [comment]
I can think of two solutions:

1. ember-cli can just set `process.setMaxListeners(1000);`
2. we can create an add-on that wraps `process.addListener` and ensures we never add more then intended.

I'm likely going to role with 1. but would love input.

**Comment by Turbo87** [comment]
I tend to agree, although `1000` seems quite high as well.

**Comment by stefanpenner** [comment]
@Turbo87 is there a downside? I figure if someone has a real problem, it would need to grow behind that.

**Comment by Turbo87** [comment]
just the gut feeling that the `10` might be there for a reason...

**Comment by stefanpenner** [comment]
https://github.com/ember-cli/ember-cli/pull/5987
