### ISSUE TITLE
Import in vendor browser_polyfill.js

### ISSUE THREAD

**Issue by Serabe** [babel/ember-cli-babel#8]
6to5 have a polyfill for the browser for certain features.

My request is for this plugin to import it by default or give one option to import it in vendor.

Currently I had to:
1. `cp node_modules/ember-cli-6to5/node_modules/broccoli-6to5-transpiler/node_modules/6to5-core/browser-polyfill.js vendor`
2. Add to Brocfile:

```
app.import ('vendor/browser-polyfill.js', {type: 'vendor', prepend: true});
```

This is needed to keep compatibility with IE8 in certain features.

**Comment by gordonkristan** [comment]
If it gets merged (which I think it will), #6 will take care of this.

**Comment by Serabe** [comment]
Thank you!

**Comment by krisselden** [comment]
would be cool if this could be driven by ember-cli's es3Safe option @stefanpenner is this something passed to addons currently?

**Comment by stefanpenner** [comment]
Ya

**Comment by stefanpenner** [comment]
#24 / #6

**Comment by shribe** [comment]
#6 is not merged, and 6to5 is now Babel, so the path is now:

`node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/browser-polyfill.js`

**Comment by knownasilya** [comment]
Isn't this now `includePolyfil`?

**Comment by Turbo87** [comment]
closing this issue as I believe @knownasilya is correct that this feature is now implemented by the `includePolyfill` option. thanks everyone!
