### ISSUE TITLE
add appveyor

### ISSUE THREAD

**Issue by stefanpenner** [babel/ember-cli-babel#82]
lets be sure our windows friends continue to have good support.

**Comment by Turbo87** [comment]
@hzoo who do we talk to to make this happen?

**Comment by stefanpenner** [comment]
I should be able to enable it on the appveyor side of things. Just haven't had a chance.  If someone can work on making it pass and stuff I can enable it

**Comment by Turbo87** [comment]
> If someone can work on making it pass and stuff

I can work on it, but it would be helpful if it was enabled for that... 😉

**Comment by rwjblue** [comment]
> it would be helpful if it was enabled for that

Yeah, just makes other PR's fail until we get it fixed.  Seems fine though for short term...

**Comment by stefanpenner** [comment]
- [ ] badge
- [ ] appveyor.yml
- [ ] make pass
