### ISSUE TITLE
Error when adding babel-plugin-transform-flow-strip-types

### ISSUE THREAD

**Issue by mesrob-fender** [babel/ember-cli-babel#94]
I’m trying to integrate ember with Flow Type Checker, but getting an error during ember builds:

```
File: ember-ajax/ajax-request.js
The Broccoli Plugin: [Babel] failed with:
TypeError: The plugin "transform-flow-strip-types" didn't export a Plugin instance
```

``` javascript
//ember-cli-build.js
module.exports = function(defaults) {
  var app = new EmberAddon(defaults, {
    babel: {
      plugins: ["transform-flow-strip-types"]
    }
  });
```

The error seems to originate from `.../node_modules/ember-cli/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/transformation/file/plugin-manager.js:165:13)`

``` javascript
    // validate Transformer instance
    if (!plugin.buildPass || plugin.constructor.name !== "Plugin") {
      throw new TypeError(messages.get("pluginNotTransformer", name));
    }
```

**Comment by oleander** [comment]
+1 I'm having the same problem.

**Comment by mrcrgl** [comment]
+1

**Comment by jasonmit** [comment]
transform-flow-strip-types is a babel 6 plugin.  ember-cli-babel currently targets babel 5.

**Comment by mesrob-fender** [comment]
@jasonmit thanks, I see. Are you aware of any timeline to integrate over to babel 6?

**Comment by jasonmit** [comment]
Work started a few months back but unsure what the current status is.

Cc @turbo87 @stefanpenner

**Comment by wooandoo** [comment]
+1

**Comment by Turbo87** [comment]
you can track the Babel 6 progress in #62. closing this as a duplicate for now.
